// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_master1_AWVALID,
        m_axi_master1_AWREADY,
        m_axi_master1_AWADDR,
        m_axi_master1_AWID,
        m_axi_master1_AWLEN,
        m_axi_master1_AWSIZE,
        m_axi_master1_AWBURST,
        m_axi_master1_AWLOCK,
        m_axi_master1_AWCACHE,
        m_axi_master1_AWPROT,
        m_axi_master1_AWQOS,
        m_axi_master1_AWREGION,
        m_axi_master1_AWUSER,
        m_axi_master1_WVALID,
        m_axi_master1_WREADY,
        m_axi_master1_WDATA,
        m_axi_master1_WSTRB,
        m_axi_master1_WLAST,
        m_axi_master1_WID,
        m_axi_master1_WUSER,
        m_axi_master1_ARVALID,
        m_axi_master1_ARREADY,
        m_axi_master1_ARADDR,
        m_axi_master1_ARID,
        m_axi_master1_ARLEN,
        m_axi_master1_ARSIZE,
        m_axi_master1_ARBURST,
        m_axi_master1_ARLOCK,
        m_axi_master1_ARCACHE,
        m_axi_master1_ARPROT,
        m_axi_master1_ARQOS,
        m_axi_master1_ARREGION,
        m_axi_master1_ARUSER,
        m_axi_master1_RVALID,
        m_axi_master1_RREADY,
        m_axi_master1_RDATA,
        m_axi_master1_RLAST,
        m_axi_master1_RID,
        m_axi_master1_RFIFONUM,
        m_axi_master1_RUSER,
        m_axi_master1_RRESP,
        m_axi_master1_BVALID,
        m_axi_master1_BREADY,
        m_axi_master1_BRESP,
        m_axi_master1_BID,
        m_axi_master1_BUSER,
        tmp_1,
        mul_ln37_1,
        tmp_4,
        y_cast,
        mul_ln18_1,
        mul_ln18,
        convWidth,
        icmp_ln44_1,
        tmp_5,
        filters,
        tmp_2,
        x_cast,
        input_r,
        acc_out,
        acc_out_ap_vld,
        grp_fu_363_p_din0,
        grp_fu_363_p_din1,
        grp_fu_363_p_dout0,
        grp_fu_363_p_ce,
        grp_fu_367_p_din0,
        grp_fu_367_p_din1,
        grp_fu_367_p_dout0,
        grp_fu_367_p_ce,
        grp_fu_386_p_din0,
        grp_fu_386_p_din1,
        grp_fu_386_p_dout0,
        grp_fu_386_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_master1_AWVALID;
input   m_axi_master1_AWREADY;
output  [31:0] m_axi_master1_AWADDR;
output  [0:0] m_axi_master1_AWID;
output  [31:0] m_axi_master1_AWLEN;
output  [2:0] m_axi_master1_AWSIZE;
output  [1:0] m_axi_master1_AWBURST;
output  [1:0] m_axi_master1_AWLOCK;
output  [3:0] m_axi_master1_AWCACHE;
output  [2:0] m_axi_master1_AWPROT;
output  [3:0] m_axi_master1_AWQOS;
output  [3:0] m_axi_master1_AWREGION;
output  [0:0] m_axi_master1_AWUSER;
output   m_axi_master1_WVALID;
input   m_axi_master1_WREADY;
output  [31:0] m_axi_master1_WDATA;
output  [3:0] m_axi_master1_WSTRB;
output   m_axi_master1_WLAST;
output  [0:0] m_axi_master1_WID;
output  [0:0] m_axi_master1_WUSER;
output   m_axi_master1_ARVALID;
input   m_axi_master1_ARREADY;
output  [31:0] m_axi_master1_ARADDR;
output  [0:0] m_axi_master1_ARID;
output  [31:0] m_axi_master1_ARLEN;
output  [2:0] m_axi_master1_ARSIZE;
output  [1:0] m_axi_master1_ARBURST;
output  [1:0] m_axi_master1_ARLOCK;
output  [3:0] m_axi_master1_ARCACHE;
output  [2:0] m_axi_master1_ARPROT;
output  [3:0] m_axi_master1_ARQOS;
output  [3:0] m_axi_master1_ARREGION;
output  [0:0] m_axi_master1_ARUSER;
input   m_axi_master1_RVALID;
output   m_axi_master1_RREADY;
input  [31:0] m_axi_master1_RDATA;
input   m_axi_master1_RLAST;
input  [0:0] m_axi_master1_RID;
input  [8:0] m_axi_master1_RFIFONUM;
input  [0:0] m_axi_master1_RUSER;
input  [1:0] m_axi_master1_RRESP;
input   m_axi_master1_BVALID;
output   m_axi_master1_BREADY;
input  [1:0] m_axi_master1_BRESP;
input  [0:0] m_axi_master1_BID;
input  [0:0] m_axi_master1_BUSER;
input  [29:0] tmp_1;
input  [29:0] mul_ln37_1;
input  [29:0] tmp_4;
input  [29:0] y_cast;
input  [95:0] mul_ln18_1;
input  [63:0] mul_ln18;
input  [31:0] convWidth;
input  [0:0] icmp_ln44_1;
input  [29:0] tmp_5;
input  [31:0] filters;
input  [29:0] tmp_2;
input  [29:0] x_cast;
input  [31:0] input_r;
output  [31:0] acc_out;
output   acc_out_ap_vld;
output  [29:0] grp_fu_363_p_din0;
output  [29:0] grp_fu_363_p_din1;
input  [29:0] grp_fu_363_p_dout0;
output   grp_fu_363_p_ce;
output  [29:0] grp_fu_367_p_din0;
output  [29:0] grp_fu_367_p_din1;
input  [29:0] grp_fu_367_p_dout0;
output   grp_fu_367_p_ce;
output  [29:0] grp_fu_386_p_din0;
output  [29:0] grp_fu_386_p_din1;
input  [29:0] grp_fu_386_p_dout0;
output   grp_fu_386_p_ce;

reg ap_idle;
reg m_axi_master1_ARVALID;
reg[31:0] m_axi_master1_ARADDR;
reg m_axi_master1_RREADY;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_state14_pp0_stage1_iter6;
reg    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln42_fu_285_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    master1_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    master1_blk_n_R;
wire    ap_block_pp0_stage1;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
reg    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] iChannel_1_reg_745;
reg    ap_block_pp0_stage1_11001;
reg   [95:0] indvar_flatten61_load_reg_750;
wire  signed [29:0] empty_fu_271_p1;
wire  signed [29:0] tmp5_fu_280_p2;
reg  signed [29:0] tmp5_reg_760;
reg   [0:0] icmp_ln42_reg_765;
reg   [0:0] icmp_ln42_reg_765_pp0_iter1_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter2_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter3_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter4_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter5_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter6_reg;
reg   [0:0] icmp_ln42_reg_765_pp0_iter7_reg;
wire   [31:0] add_ln42_1_fu_290_p2;
reg   [31:0] add_ln42_1_reg_769;
wire  signed [29:0] empty_33_fu_296_p1;
reg  signed [29:0] empty_33_reg_774;
wire  signed [29:0] tmp5_mid1_fu_300_p2;
reg  signed [29:0] tmp5_mid1_reg_779;
reg   [29:0] p_cast4_reg_784;
reg   [63:0] indvar_flatten_load_reg_789;
wire   [0:0] icmp_ln43_fu_317_p2;
reg   [0:0] icmp_ln43_reg_794;
reg   [0:0] icmp_ln43_reg_794_pp0_iter2_reg;
reg   [29:0] tmp6_cast_reg_806;
reg   [29:0] p_cast4_mid1_reg_812;
wire   [29:0] grp_fu_326_p2;
reg   [29:0] tmp6_cast_mid1_reg_817;
reg   [31:0] cx_load_reg_823;
wire   [0:0] select_ln40_5_fu_429_p3;
reg   [0:0] select_ln40_5_reg_828;
wire  signed [29:0] select_ln40_7_fu_457_p3;
reg  signed [29:0] select_ln40_7_reg_833;
wire  signed [29:0] select_ln40_8_fu_465_p3;
reg  signed [29:0] select_ln40_8_reg_838;
wire   [31:0] select_ln40_6_fu_490_p3;
reg   [31:0] select_ln40_6_reg_843;
reg   [31:0] select_ln40_6_reg_843_pp0_iter3_reg;
wire   [29:0] grp_fu_497_p2;
reg   [29:0] mul_ln40_reg_849;
wire   [29:0] grp_fu_501_p2;
reg   [29:0] mul_ln40_1_reg_854;
reg   [29:0] sext_ln44_1_mid2_v_reg_859;
wire   [31:0] add_ln47_fu_569_p2;
reg   [31:0] add_ln47_reg_864;
wire   [31:0] add_ln48_fu_583_p2;
reg   [31:0] add_ln48_reg_875;
reg  signed [31:0] filterValue_reg_886;
reg  signed [31:0] pixelValue_reg_891;
reg   [31:0] trunc_ln1_reg_906;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [31:0] acc_fu_102;
wire   [31:0] acc_1_fu_619_p2;
wire    ap_loop_init;
reg   [31:0] cx_fu_106;
wire   [31:0] add_ln44_fu_505_p2;
reg   [31:0] cy_fu_110;
wire   [31:0] select_ln43_fu_473_p3;
reg   [63:0] indvar_flatten_fu_114;
wire   [63:0] select_ln43_1_fu_351_p3;
reg   [31:0] iChannel_fu_118;
wire   [31:0] select_ln42_fu_330_p3;
reg   [95:0] indvar_flatten61_fu_122;
wire   [95:0] add_ln42_fu_309_p2;
reg    ap_block_pp0_stage1_01001;
wire   [63:0] add_ln43_1_fu_346_p2;
wire   [29:0] tmp1_fu_366_p2;
wire   [29:0] empty_32_fu_370_p1;
wire   [29:0] tmp1_mid1_fu_400_p2;
wire   [29:0] tmp7_fu_380_p2;
wire   [29:0] tmp3_fu_374_p2;
wire   [0:0] icmp_ln44_fu_424_p2;
wire   [31:0] select_ln40_fu_388_p3;
wire   [31:0] add_ln43_fu_435_p2;
wire   [29:0] select_ln40_2_fu_404_p3;
wire   [29:0] empty_34_fu_441_p1;
wire   [29:0] select_ln40_1_fu_395_p3;
wire   [29:0] tmp7_mid1_fu_451_p2;
wire   [29:0] select_ln40_3_fu_411_p3;
wire   [29:0] tmp3_mid1_fu_445_p2;
wire   [29:0] select_ln40_4_fu_417_p3;
wire   [0:0] or_ln40_fu_486_p2;
wire   [31:0] sext_ln44_mid2_v_v_v_v_fu_516_p3;
wire   [31:0] add_ln40_fu_523_p2;
wire   [29:0] sext_ln44_mid2_v_fu_528_p4;
wire   [29:0] add_ln40_1_fu_542_p2;
wire   [31:0] sext_ln44_1_mid2_v_v_v_v_fu_546_p3;
wire   [31:0] add_ln40_2_fu_554_p2;
wire  signed [31:0] sext_ln40_fu_538_p1;
wire  signed [31:0] sext_ln40_1_fu_574_p1;
wire   [51:0] grp_fu_600_p2;
reg    grp_fu_275_ce;
reg    grp_fu_305_ce;
reg    grp_fu_322_ce;
reg    grp_fu_326_ce;
reg    grp_fu_497_ce;
reg    grp_fu_501_ce;
reg    grp_fu_600_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to9;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp5_mid1_reg_779),
    .din1(tmp_4),
    .ce(grp_fu_326_ce),
    .dout(grp_fu_326_p2)
);

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln40_7_reg_833),
    .din1(tmp_5),
    .ce(grp_fu_497_ce),
    .dout(grp_fu_497_p2)
);

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln40_8_reg_838),
    .din1(tmp_2),
    .ce(grp_fu_501_ce),
    .dout(grp_fu_501_p2)
);

Conv2D_HW_mul_32s_32s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 52 ))
mul_32s_32s_52_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pixelValue_reg_891),
    .din1(filterValue_reg_886),
    .ce(grp_fu_600_ce),
    .dout(grp_fu_600_p2)
);

Conv2D_HW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_fu_102 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        acc_fu_102 <= acc_1_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cx_fu_106 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        cx_fu_106 <= add_ln44_fu_505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            cy_fu_110 <= 32'd0;
        end else if (((icmp_ln42_reg_765_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            cy_fu_110 <= select_ln43_fu_473_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            iChannel_fu_118 <= 32'd0;
        end else if (((icmp_ln42_reg_765 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            iChannel_fu_118 <= select_ln42_fu_330_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten61_fu_122 <= 96'd0;
        end else if (((icmp_ln42_reg_765 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten61_fu_122 <= add_ln42_fu_309_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_fu_114 <= 64'd0;
    end else if (((icmp_ln42_reg_765 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten_fu_114 <= select_ln43_1_fu_351_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln42_fu_285_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln42_1_reg_769 <= add_ln42_1_fu_290_p2;
        empty_33_reg_774 <= empty_33_fu_296_p1;
        tmp5_mid1_reg_779 <= tmp5_mid1_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln47_reg_864 <= add_ln47_fu_569_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        filterValue_reg_886 <= m_axi_master1_RDATA;
        iChannel_1_reg_745 <= iChannel_fu_118;
        icmp_ln42_reg_765 <= icmp_ln42_fu_285_p2;
        icmp_ln42_reg_765_pp0_iter1_reg <= icmp_ln42_reg_765;
        icmp_ln42_reg_765_pp0_iter2_reg <= icmp_ln42_reg_765_pp0_iter1_reg;
        icmp_ln42_reg_765_pp0_iter3_reg <= icmp_ln42_reg_765_pp0_iter2_reg;
        icmp_ln42_reg_765_pp0_iter4_reg <= icmp_ln42_reg_765_pp0_iter3_reg;
        icmp_ln42_reg_765_pp0_iter5_reg <= icmp_ln42_reg_765_pp0_iter4_reg;
        icmp_ln42_reg_765_pp0_iter6_reg <= icmp_ln42_reg_765_pp0_iter5_reg;
        icmp_ln42_reg_765_pp0_iter7_reg <= icmp_ln42_reg_765_pp0_iter6_reg;
        indvar_flatten61_load_reg_750 <= indvar_flatten61_fu_122;
        select_ln40_6_reg_843 <= select_ln40_6_fu_490_p3;
        select_ln40_6_reg_843_pp0_iter3_reg <= select_ln40_6_reg_843;
        sext_ln44_1_mid2_v_reg_859 <= {{add_ln40_2_fu_554_p2[31:2]}};
        tmp5_reg_760 <= tmp5_fu_280_p2;
        tmp6_cast_reg_806 <= grp_fu_367_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln48_reg_875 <= add_ln48_fu_583_p2;
        icmp_ln43_reg_794_pp0_iter2_reg <= icmp_ln43_reg_794;
        mul_ln40_1_reg_854 <= grp_fu_501_p2;
        mul_ln40_reg_849 <= grp_fu_497_p2;
        p_cast4_reg_784 <= grp_fu_363_p_dout0;
        pixelValue_reg_891 <= m_axi_master1_RDATA;
        trunc_ln1_reg_906 <= {{grp_fu_600_p2[51:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_765_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cx_load_reg_823 <= cx_fu_106;
        select_ln40_5_reg_828 <= select_ln40_5_fu_429_p3;
        select_ln40_7_reg_833 <= select_ln40_7_fu_457_p3;
        select_ln40_8_reg_838 <= select_ln40_8_fu_465_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_765 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln43_reg_794 <= icmp_ln43_fu_317_p2;
        indvar_flatten_load_reg_789 <= indvar_flatten_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_765 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        p_cast4_mid1_reg_812 <= grp_fu_386_p_dout0;
        tmp6_cast_mid1_reg_817 <= grp_fu_326_p2;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_765_pp0_iter7_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln42_fu_285_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_765_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to9 = 1'b1;
    end else begin
        ap_idle_pp0_1to9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_275_ce = 1'b1;
    end else begin
        grp_fu_275_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_305_ce = 1'b1;
    end else begin
        grp_fu_305_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_322_ce = 1'b1;
    end else begin
        grp_fu_322_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_326_ce = 1'b1;
    end else begin
        grp_fu_326_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_497_ce = 1'b1;
    end else begin
        grp_fu_497_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_501_ce = 1'b1;
    end else begin
        grp_fu_501_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_600_ce = 1'b1;
    end else begin
        grp_fu_600_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
            m_axi_master1_ARADDR = add_ln48_reg_875;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            m_axi_master1_ARADDR = add_ln47_reg_864;
        end else begin
            m_axi_master1_ARADDR = 'bx;
        end
    end else begin
        m_axi_master1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_master1_ARVALID = 1'b1;
    end else begin
        m_axi_master1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_master1_RREADY = 1'b1;
    end else begin
        m_axi_master1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        master1_blk_n_AR = m_axi_master1_ARREADY;
    end else begin
        master1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        master1_blk_n_R = m_axi_master1_RVALID;
    end else begin
        master1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to9 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_619_p2 = (trunc_ln1_reg_906 + acc_fu_102);

assign acc_out = acc_fu_102;

assign add_ln40_1_fu_542_p2 = (mul_ln40_1_reg_854 + x_cast);

assign add_ln40_2_fu_554_p2 = (sext_ln44_1_mid2_v_v_v_v_fu_546_p3 + input_r);

assign add_ln40_fu_523_p2 = (sext_ln44_mid2_v_v_v_v_fu_516_p3 + filters);

assign add_ln42_1_fu_290_p2 = (iChannel_fu_118 + 32'd1);

assign add_ln42_fu_309_p2 = (indvar_flatten61_load_reg_750 + 96'd1);

assign add_ln43_1_fu_346_p2 = (indvar_flatten_load_reg_789 + 64'd1);

assign add_ln43_fu_435_p2 = (select_ln40_fu_388_p3 + 32'd1);

assign add_ln44_fu_505_p2 = (select_ln40_6_fu_490_p3 + 32'd1);

assign add_ln47_fu_569_p2 = ($signed(select_ln40_6_reg_843) + $signed(sext_ln40_fu_538_p1));

assign add_ln48_fu_583_p2 = ($signed(select_ln40_6_reg_843_pp0_iter3_reg) + $signed(sext_ln40_1_fu_574_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_master1_RVALID == 1'b0)) | ((m_axi_master1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_master1_RVALID == 1'b0)) | ((m_axi_master1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (m_axi_master1_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (m_axi_master1_RVALID == 1'b0)) | ((m_axi_master1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (m_axi_master1_RVALID == 1'b0)) | ((m_axi_master1_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage1_iter7 = (m_axi_master1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter8 = (m_axi_master1_RVALID == 1'b0);
end

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign empty_32_fu_370_p1 = cy_fu_110[29:0];

assign empty_33_fu_296_p1 = add_ln42_1_fu_290_p2[29:0];

assign empty_34_fu_441_p1 = add_ln43_fu_435_p2[29:0];

assign empty_fu_271_p1 = iChannel_fu_118[29:0];

assign grp_fu_363_p_ce = grp_fu_275_ce;

assign grp_fu_363_p_din0 = empty_fu_271_p1;

assign grp_fu_363_p_din1 = tmp_1;

assign grp_fu_367_p_ce = grp_fu_305_ce;

assign grp_fu_367_p_din0 = tmp5_reg_760;

assign grp_fu_367_p_din1 = tmp_4;

assign grp_fu_386_p_ce = grp_fu_322_ce;

assign grp_fu_386_p_din0 = empty_33_reg_774;

assign grp_fu_386_p_din1 = tmp_1;

assign icmp_ln42_fu_285_p2 = ((indvar_flatten61_fu_122 == mul_ln18_1) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_317_p2 = ((indvar_flatten_fu_114 == mul_ln18) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_424_p2 = ((cx_fu_106 == convWidth) ? 1'b1 : 1'b0);

assign m_axi_master1_ARBURST = 2'd0;

assign m_axi_master1_ARCACHE = 4'd0;

assign m_axi_master1_ARID = 1'd0;

assign m_axi_master1_ARLEN = 32'd1;

assign m_axi_master1_ARLOCK = 2'd0;

assign m_axi_master1_ARPROT = 3'd0;

assign m_axi_master1_ARQOS = 4'd0;

assign m_axi_master1_ARREGION = 4'd0;

assign m_axi_master1_ARSIZE = 3'd0;

assign m_axi_master1_ARUSER = 1'd0;

assign m_axi_master1_AWADDR = 32'd0;

assign m_axi_master1_AWBURST = 2'd0;

assign m_axi_master1_AWCACHE = 4'd0;

assign m_axi_master1_AWID = 1'd0;

assign m_axi_master1_AWLEN = 32'd0;

assign m_axi_master1_AWLOCK = 2'd0;

assign m_axi_master1_AWPROT = 3'd0;

assign m_axi_master1_AWQOS = 4'd0;

assign m_axi_master1_AWREGION = 4'd0;

assign m_axi_master1_AWSIZE = 3'd0;

assign m_axi_master1_AWUSER = 1'd0;

assign m_axi_master1_AWVALID = 1'b0;

assign m_axi_master1_BREADY = 1'b0;

assign m_axi_master1_WDATA = 32'd0;

assign m_axi_master1_WID = 1'd0;

assign m_axi_master1_WLAST = 1'b0;

assign m_axi_master1_WSTRB = 4'd0;

assign m_axi_master1_WUSER = 1'd0;

assign m_axi_master1_WVALID = 1'b0;

assign or_ln40_fu_486_p2 = (select_ln40_5_reg_828 | icmp_ln43_reg_794_pp0_iter2_reg);

assign select_ln40_1_fu_395_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? tmp6_cast_mid1_reg_817 : tmp6_cast_reg_806);

assign select_ln40_2_fu_404_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? tmp1_mid1_fu_400_p2 : tmp1_fu_366_p2);

assign select_ln40_3_fu_411_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? tmp6_cast_mid1_reg_817 : tmp7_fu_380_p2);

assign select_ln40_4_fu_417_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? tmp1_mid1_fu_400_p2 : tmp3_fu_374_p2);

assign select_ln40_5_fu_429_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? icmp_ln44_1 : icmp_ln44_fu_424_p2);

assign select_ln40_6_fu_490_p3 = ((or_ln40_fu_486_p2[0:0] == 1'b1) ? 32'd0 : cx_load_reg_823);

assign select_ln40_7_fu_457_p3 = ((select_ln40_5_fu_429_p3[0:0] == 1'b1) ? tmp7_mid1_fu_451_p2 : select_ln40_3_fu_411_p3);

assign select_ln40_8_fu_465_p3 = ((select_ln40_5_fu_429_p3[0:0] == 1'b1) ? tmp3_mid1_fu_445_p2 : select_ln40_4_fu_417_p3);

assign select_ln40_fu_388_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? 32'd0 : cy_fu_110);

assign select_ln42_fu_330_p3 = ((icmp_ln43_fu_317_p2[0:0] == 1'b1) ? add_ln42_1_reg_769 : iChannel_1_reg_745);

assign select_ln43_1_fu_351_p3 = ((icmp_ln43_reg_794[0:0] == 1'b1) ? 64'd1 : add_ln43_1_fu_346_p2);

assign select_ln43_fu_473_p3 = ((select_ln40_5_fu_429_p3[0:0] == 1'b1) ? add_ln43_fu_435_p2 : select_ln40_fu_388_p3);

assign sext_ln40_1_fu_574_p1 = $signed(sext_ln44_1_mid2_v_reg_859);

assign sext_ln40_fu_538_p1 = $signed(sext_ln44_mid2_v_fu_528_p4);

assign sext_ln44_1_mid2_v_v_v_v_fu_546_p3 = {{add_ln40_1_fu_542_p2}, {2'd0}};

assign sext_ln44_mid2_v_fu_528_p4 = {{add_ln40_fu_523_p2[31:2]}};

assign sext_ln44_mid2_v_v_v_v_fu_516_p3 = {{mul_ln40_reg_849}, {2'd0}};

assign tmp1_fu_366_p2 = (y_cast + p_cast4_reg_784);

assign tmp1_mid1_fu_400_p2 = (y_cast + p_cast4_mid1_reg_812);

assign tmp3_fu_374_p2 = (tmp1_fu_366_p2 + empty_32_fu_370_p1);

assign tmp3_mid1_fu_445_p2 = (select_ln40_2_fu_404_p3 + empty_34_fu_441_p1);

assign tmp5_fu_280_p2 = ($signed(empty_fu_271_p1) + $signed(mul_ln37_1));

assign tmp5_mid1_fu_300_p2 = ($signed(empty_33_fu_296_p1) + $signed(mul_ln37_1));

assign tmp7_fu_380_p2 = (empty_32_fu_370_p1 + tmp6_cast_reg_806);

assign tmp7_mid1_fu_451_p2 = (empty_34_fu_441_p1 + select_ln40_1_fu_395_p3);

endmodule //Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6
