// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5330,HLS_SYN_LUT=4938,HLS_VERSION=2022_2}" *)

module Conv2D_HW (
        ap_clk,
        ap_rst_n,
        m_axi_master1_AWVALID,
        m_axi_master1_AWREADY,
        m_axi_master1_AWADDR,
        m_axi_master1_AWID,
        m_axi_master1_AWLEN,
        m_axi_master1_AWSIZE,
        m_axi_master1_AWBURST,
        m_axi_master1_AWLOCK,
        m_axi_master1_AWCACHE,
        m_axi_master1_AWPROT,
        m_axi_master1_AWQOS,
        m_axi_master1_AWREGION,
        m_axi_master1_AWUSER,
        m_axi_master1_WVALID,
        m_axi_master1_WREADY,
        m_axi_master1_WDATA,
        m_axi_master1_WSTRB,
        m_axi_master1_WLAST,
        m_axi_master1_WID,
        m_axi_master1_WUSER,
        m_axi_master1_ARVALID,
        m_axi_master1_ARREADY,
        m_axi_master1_ARADDR,
        m_axi_master1_ARID,
        m_axi_master1_ARLEN,
        m_axi_master1_ARSIZE,
        m_axi_master1_ARBURST,
        m_axi_master1_ARLOCK,
        m_axi_master1_ARCACHE,
        m_axi_master1_ARPROT,
        m_axi_master1_ARQOS,
        m_axi_master1_ARREGION,
        m_axi_master1_ARUSER,
        m_axi_master1_RVALID,
        m_axi_master1_RREADY,
        m_axi_master1_RDATA,
        m_axi_master1_RLAST,
        m_axi_master1_RID,
        m_axi_master1_RUSER,
        m_axi_master1_RRESP,
        m_axi_master1_BVALID,
        m_axi_master1_BREADY,
        m_axi_master1_BRESP,
        m_axi_master1_BID,
        m_axi_master1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_MASTER1_ID_WIDTH = 1;
parameter    C_M_AXI_MASTER1_ADDR_WIDTH = 32;
parameter    C_M_AXI_MASTER1_DATA_WIDTH = 32;
parameter    C_M_AXI_MASTER1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MASTER1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MASTER1_WUSER_WIDTH = 1;
parameter    C_M_AXI_MASTER1_RUSER_WIDTH = 1;
parameter    C_M_AXI_MASTER1_BUSER_WIDTH = 1;
parameter    C_M_AXI_MASTER1_USER_VALUE = 0;
parameter    C_M_AXI_MASTER1_PROT_VALUE = 0;
parameter    C_M_AXI_MASTER1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MASTER1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_master1_AWVALID;
input   m_axi_master1_AWREADY;
output  [C_M_AXI_MASTER1_ADDR_WIDTH - 1:0] m_axi_master1_AWADDR;
output  [C_M_AXI_MASTER1_ID_WIDTH - 1:0] m_axi_master1_AWID;
output  [7:0] m_axi_master1_AWLEN;
output  [2:0] m_axi_master1_AWSIZE;
output  [1:0] m_axi_master1_AWBURST;
output  [1:0] m_axi_master1_AWLOCK;
output  [3:0] m_axi_master1_AWCACHE;
output  [2:0] m_axi_master1_AWPROT;
output  [3:0] m_axi_master1_AWQOS;
output  [3:0] m_axi_master1_AWREGION;
output  [C_M_AXI_MASTER1_AWUSER_WIDTH - 1:0] m_axi_master1_AWUSER;
output   m_axi_master1_WVALID;
input   m_axi_master1_WREADY;
output  [C_M_AXI_MASTER1_DATA_WIDTH - 1:0] m_axi_master1_WDATA;
output  [C_M_AXI_MASTER1_WSTRB_WIDTH - 1:0] m_axi_master1_WSTRB;
output   m_axi_master1_WLAST;
output  [C_M_AXI_MASTER1_ID_WIDTH - 1:0] m_axi_master1_WID;
output  [C_M_AXI_MASTER1_WUSER_WIDTH - 1:0] m_axi_master1_WUSER;
output   m_axi_master1_ARVALID;
input   m_axi_master1_ARREADY;
output  [C_M_AXI_MASTER1_ADDR_WIDTH - 1:0] m_axi_master1_ARADDR;
output  [C_M_AXI_MASTER1_ID_WIDTH - 1:0] m_axi_master1_ARID;
output  [7:0] m_axi_master1_ARLEN;
output  [2:0] m_axi_master1_ARSIZE;
output  [1:0] m_axi_master1_ARBURST;
output  [1:0] m_axi_master1_ARLOCK;
output  [3:0] m_axi_master1_ARCACHE;
output  [2:0] m_axi_master1_ARPROT;
output  [3:0] m_axi_master1_ARQOS;
output  [3:0] m_axi_master1_ARREGION;
output  [C_M_AXI_MASTER1_ARUSER_WIDTH - 1:0] m_axi_master1_ARUSER;
input   m_axi_master1_RVALID;
output   m_axi_master1_RREADY;
input  [C_M_AXI_MASTER1_DATA_WIDTH - 1:0] m_axi_master1_RDATA;
input   m_axi_master1_RLAST;
input  [C_M_AXI_MASTER1_ID_WIDTH - 1:0] m_axi_master1_RID;
input  [C_M_AXI_MASTER1_RUSER_WIDTH - 1:0] m_axi_master1_RUSER;
input  [1:0] m_axi_master1_RRESP;
input   m_axi_master1_BVALID;
output   m_axi_master1_BREADY;
input  [1:0] m_axi_master1_BRESP;
input  [C_M_AXI_MASTER1_ID_WIDTH - 1:0] m_axi_master1_BID;
input  [C_M_AXI_MASTER1_BUSER_WIDTH - 1:0] m_axi_master1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] input_r;
wire   [31:0] output_r;
wire   [31:0] filters;
wire   [31:0] numChannels;
wire   [31:0] numFilters;
wire   [31:0] inputWidth;
wire   [31:0] inputHeight;
wire   [31:0] convWidth;
wire   [31:0] convHeight;
reg    master1_blk_n_W;
wire    ap_CS_fsm_state19;
reg    master1_blk_n_B;
wire    ap_CS_fsm_state24;
reg    master1_blk_n_AW;
wire    ap_CS_fsm_state16;
reg   [31:0] convHeight_read_reg_481;
reg   [31:0] convWidth_read_reg_486;
reg   [31:0] inputHeight_read_reg_493;
reg   [31:0] inputWidth_read_reg_498;
reg   [31:0] numFilters_read_reg_503;
reg   [31:0] numChannels_read_reg_508;
reg   [31:0] filters_read_reg_513;
reg   [31:0] output_r_read_reg_518;
reg   [31:0] input_r_read_reg_523;
wire   [29:0] empty_fu_224_p1;
reg   [29:0] empty_reg_534;
wire   [29:0] empty_35_fu_228_p1;
reg   [29:0] empty_35_reg_540;
wire  signed [29:0] empty_37_fu_232_p1;
reg  signed [29:0] empty_37_reg_546;
wire   [29:0] empty_39_fu_236_p1;
reg   [29:0] empty_39_reg_551;
wire   [29:0] empty_40_fu_240_p1;
reg   [29:0] empty_40_reg_556;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_265_p2;
reg   [63:0] mul_ln18_reg_571;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [31:0] sub_fu_283_p2;
reg   [31:0] sub_reg_587;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [31:0] sub6_fu_300_p2;
reg   [31:0] sub6_reg_603;
wire    ap_CS_fsm_state8;
wire  signed [29:0] empty_36_fu_305_p2;
reg  signed [29:0] empty_36_reg_609;
wire  signed [29:0] empty_38_fu_310_p2;
reg  signed [29:0] empty_38_reg_614;
wire   [95:0] grp_fu_277_p2;
reg   [95:0] mul_ln18_1_reg_619;
wire   [63:0] grp_fu_294_p2;
reg   [63:0] mul_ln18_2_reg_624;
wire   [0:0] icmp_ln44_fu_315_p2;
reg   [0:0] icmp_ln44_reg_629;
wire   [63:0] add_ln37_fu_328_p2;
reg   [63:0] add_ln37_reg_637;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln38_fu_340_p2;
reg   [0:0] icmp_ln38_reg_645;
wire   [0:0] icmp_ln37_fu_323_p2;
wire   [31:0] select_ln37_1_fu_351_p3;
reg   [31:0] select_ln37_1_reg_650;
wire  signed [29:0] trunc_ln37_fu_359_p1;
reg  signed [29:0] trunc_ln37_reg_655;
wire   [29:0] grp_fu_363_p2;
reg   [29:0] mul_ln37_reg_661;
wire    ap_CS_fsm_state11;
wire   [29:0] grp_fu_367_p2;
reg   [29:0] mul_ln37_1_reg_666;
wire   [31:0] select_ln37_fu_371_p3;
reg   [31:0] select_ln37_reg_671;
wire    ap_CS_fsm_state12;
wire   [29:0] empty_43_fu_377_p1;
reg   [29:0] empty_43_reg_676;
wire  signed [29:0] tmp_fu_381_p2;
reg  signed [29:0] tmp_reg_681;
wire   [29:0] grp_fu_386_p2;
reg   [29:0] p_cast3_reg_686;
wire    ap_CS_fsm_state14;
reg   [29:0] trunc_ln_reg_691;
wire    ap_CS_fsm_state15;
wire   [31:0] add_ln39_fu_427_p2;
reg   [31:0] add_ln39_reg_705;
wire    ap_CS_fsm_state17;
wire   [29:0] empty_41_fu_433_p1;
reg   [29:0] empty_41_reg_710;
wire   [0:0] icmp_ln39_fu_422_p2;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WSTRB;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_BREADY;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out_ap_vld;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0;
wire  signed [29:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce;
reg    master1_AWVALID;
wire    master1_AWREADY;
reg    master1_WVALID;
wire    master1_WREADY;
reg    master1_ARVALID;
wire    master1_ARREADY;
wire    master1_RVALID;
reg    master1_RREADY;
wire   [31:0] master1_RDATA;
wire   [8:0] master1_RFIFONUM;
wire    master1_BVALID;
reg    master1_BREADY;
reg   [31:0] x_reg_193;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg;
wire    ap_CS_fsm_state18;
wire   [31:0] sext_ln39_fu_412_p1;
reg   [31:0] y_fu_108;
wire   [31:0] add_ln38_fu_438_p2;
reg   [31:0] iFilter_fu_112;
reg   [63:0] indvar_flatten68_fu_116;
wire   [31:0] grp_fu_265_p0;
wire   [31:0] grp_fu_265_p1;
wire   [31:0] grp_fu_277_p0;
wire   [63:0] grp_fu_277_p1;
wire   [31:0] grp_fu_294_p0;
wire   [31:0] grp_fu_294_p1;
wire   [31:0] add_ln37_1_fu_345_p2;
reg  signed [29:0] grp_fu_363_p0;
reg  signed [29:0] grp_fu_363_p1;
wire    ap_CS_fsm_state10;
reg  signed [29:0] grp_fu_367_p0;
reg  signed [29:0] grp_fu_367_p1;
reg  signed [29:0] grp_fu_386_p0;
reg  signed [29:0] grp_fu_386_p1;
wire    ap_CS_fsm_state13;
wire   [31:0] tmp_6_fu_390_p3;
wire   [31:0] empty_44_fu_397_p2;
reg    grp_fu_363_ce;
reg    grp_fu_367_ce;
reg    grp_fu_386_ce;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire   [63:0] grp_fu_265_p00;
wire   [63:0] grp_fu_265_p10;
wire   [95:0] grp_fu_277_p00;
wire   [95:0] grp_fu_277_p10;
wire   [63:0] grp_fu_294_p00;
wire   [63:0] grp_fu_294_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg = 1'b0;
end

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready),
    .m_axi_master1_AWVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWVALID),
    .m_axi_master1_AWREADY(1'b0),
    .m_axi_master1_AWADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWADDR),
    .m_axi_master1_AWID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWID),
    .m_axi_master1_AWLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLEN),
    .m_axi_master1_AWSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWSIZE),
    .m_axi_master1_AWBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWBURST),
    .m_axi_master1_AWLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLOCK),
    .m_axi_master1_AWCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWCACHE),
    .m_axi_master1_AWPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWPROT),
    .m_axi_master1_AWQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWQOS),
    .m_axi_master1_AWREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWREGION),
    .m_axi_master1_AWUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWUSER),
    .m_axi_master1_WVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WVALID),
    .m_axi_master1_WREADY(1'b0),
    .m_axi_master1_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WDATA),
    .m_axi_master1_WSTRB(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WSTRB),
    .m_axi_master1_WLAST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WLAST),
    .m_axi_master1_WID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WID),
    .m_axi_master1_WUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WUSER),
    .m_axi_master1_ARVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID),
    .m_axi_master1_ARREADY(master1_ARREADY),
    .m_axi_master1_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR),
    .m_axi_master1_ARID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARID),
    .m_axi_master1_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN),
    .m_axi_master1_ARSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARSIZE),
    .m_axi_master1_ARBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARBURST),
    .m_axi_master1_ARLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLOCK),
    .m_axi_master1_ARCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARCACHE),
    .m_axi_master1_ARPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARPROT),
    .m_axi_master1_ARQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARQOS),
    .m_axi_master1_ARREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARREGION),
    .m_axi_master1_ARUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARUSER),
    .m_axi_master1_RVALID(master1_RVALID),
    .m_axi_master1_RREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY),
    .m_axi_master1_RDATA(master1_RDATA),
    .m_axi_master1_RLAST(1'b0),
    .m_axi_master1_RID(1'd0),
    .m_axi_master1_RFIFONUM(master1_RFIFONUM),
    .m_axi_master1_RUSER(1'd0),
    .m_axi_master1_RRESP(2'd0),
    .m_axi_master1_BVALID(1'b0),
    .m_axi_master1_BREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_BREADY),
    .m_axi_master1_BRESP(2'd0),
    .m_axi_master1_BID(1'd0),
    .m_axi_master1_BUSER(1'd0),
    .tmp_1(empty_reg_534),
    .mul_ln37_1(mul_ln37_1_reg_666),
    .tmp_4(empty_39_reg_551),
    .y_cast(empty_43_reg_676),
    .mul_ln18_1(mul_ln18_1_reg_619),
    .mul_ln18(mul_ln18_reg_571),
    .convWidth(convWidth_read_reg_486),
    .icmp_ln44_1(icmp_ln44_reg_629),
    .tmp_5(empty_40_reg_556),
    .filters(filters_read_reg_513),
    .tmp_2(empty_35_reg_540),
    .x_cast(empty_41_reg_710),
    .input_r(input_r_read_reg_523),
    .acc_out(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out),
    .acc_out_ap_vld(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out_ap_vld),
    .grp_fu_363_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0),
    .grp_fu_363_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1),
    .grp_fu_363_p_dout0(grp_fu_363_p2),
    .grp_fu_363_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce),
    .grp_fu_367_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0),
    .grp_fu_367_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1),
    .grp_fu_367_p_dout0(grp_fu_367_p2),
    .grp_fu_367_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce),
    .grp_fu_386_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0),
    .grp_fu_386_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1),
    .grp_fu_386_p_dout0(grp_fu_386_p2),
    .grp_fu_386_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce)
);

Conv2D_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .filters(filters),
    .numChannels(numChannels),
    .numFilters(numFilters),
    .inputWidth(inputWidth),
    .inputHeight(inputHeight),
    .convWidth(convWidth),
    .convHeight(convHeight),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Conv2D_HW_master1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MASTER1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MASTER1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MASTER1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MASTER1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MASTER1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MASTER1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MASTER1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MASTER1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MASTER1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MASTER1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MASTER1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
master1_m_axi_U(
    .AWVALID(m_axi_master1_AWVALID),
    .AWREADY(m_axi_master1_AWREADY),
    .AWADDR(m_axi_master1_AWADDR),
    .AWID(m_axi_master1_AWID),
    .AWLEN(m_axi_master1_AWLEN),
    .AWSIZE(m_axi_master1_AWSIZE),
    .AWBURST(m_axi_master1_AWBURST),
    .AWLOCK(m_axi_master1_AWLOCK),
    .AWCACHE(m_axi_master1_AWCACHE),
    .AWPROT(m_axi_master1_AWPROT),
    .AWQOS(m_axi_master1_AWQOS),
    .AWREGION(m_axi_master1_AWREGION),
    .AWUSER(m_axi_master1_AWUSER),
    .WVALID(m_axi_master1_WVALID),
    .WREADY(m_axi_master1_WREADY),
    .WDATA(m_axi_master1_WDATA),
    .WSTRB(m_axi_master1_WSTRB),
    .WLAST(m_axi_master1_WLAST),
    .WID(m_axi_master1_WID),
    .WUSER(m_axi_master1_WUSER),
    .ARVALID(m_axi_master1_ARVALID),
    .ARREADY(m_axi_master1_ARREADY),
    .ARADDR(m_axi_master1_ARADDR),
    .ARID(m_axi_master1_ARID),
    .ARLEN(m_axi_master1_ARLEN),
    .ARSIZE(m_axi_master1_ARSIZE),
    .ARBURST(m_axi_master1_ARBURST),
    .ARLOCK(m_axi_master1_ARLOCK),
    .ARCACHE(m_axi_master1_ARCACHE),
    .ARPROT(m_axi_master1_ARPROT),
    .ARQOS(m_axi_master1_ARQOS),
    .ARREGION(m_axi_master1_ARREGION),
    .ARUSER(m_axi_master1_ARUSER),
    .RVALID(m_axi_master1_RVALID),
    .RREADY(m_axi_master1_RREADY),
    .RDATA(m_axi_master1_RDATA),
    .RLAST(m_axi_master1_RLAST),
    .RID(m_axi_master1_RID),
    .RUSER(m_axi_master1_RUSER),
    .RRESP(m_axi_master1_RRESP),
    .BVALID(m_axi_master1_BVALID),
    .BREADY(m_axi_master1_BREADY),
    .BRESP(m_axi_master1_BRESP),
    .BID(m_axi_master1_BID),
    .BUSER(m_axi_master1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(master1_ARVALID),
    .I_ARREADY(master1_ARREADY),
    .I_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR),
    .I_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN),
    .I_RVALID(master1_RVALID),
    .I_RREADY(master1_RREADY),
    .I_RDATA(master1_RDATA),
    .I_RFIFONUM(master1_RFIFONUM),
    .I_AWVALID(master1_AWVALID),
    .I_AWREADY(master1_AWREADY),
    .I_AWADDR(sext_ln39_fu_412_p1),
    .I_AWLEN(sub6_reg_603),
    .I_WVALID(master1_WVALID),
    .I_WREADY(master1_WREADY),
    .I_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out),
    .I_WSTRB(4'd15),
    .I_BVALID(master1_BVALID),
    .I_BREADY(master1_BREADY)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U25(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_265_p0),
    .din1(grp_fu_265_p1),
    .ce(1'b1),
    .dout(grp_fu_265_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U26(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_277_p0),
    .din1(grp_fu_277_p1),
    .ce(1'b1),
    .dout(grp_fu_277_p2)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U27(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_294_p0),
    .din1(grp_fu_294_p1),
    .ce(1'b1),
    .dout(grp_fu_294_p2)
);

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U28(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_363_p0),
    .din1(grp_fu_363_p1),
    .ce(grp_fu_363_ce),
    .dout(grp_fu_363_p2)
);

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U29(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_367_p0),
    .din1(grp_fu_367_p1),
    .ce(grp_fu_367_ce),
    .dout(grp_fu_367_p2)
);

Conv2D_HW_mul_30s_30s_30_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_386_p0),
    .din1(grp_fu_386_p1),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln39_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iFilter_fu_112 <= 32'd0;
    end else if (((icmp_ln39_fu_422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        iFilter_fu_112 <= select_ln37_1_reg_650;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten68_fu_116 <= 64'd0;
    end else if (((icmp_ln39_fu_422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        indvar_flatten68_fu_116 <= add_ln37_reg_637;
    end
end

always @ (posedge ap_clk) begin
    if (((master1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        x_reg_193 <= 32'd0;
    end else if (((master1_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        x_reg_193 <= add_ln39_reg_705;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_108 <= 32'd0;
    end else if (((icmp_ln39_fu_422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        y_fu_108 <= add_ln38_fu_438_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln37_reg_637 <= add_ln37_fu_328_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln39_reg_705 <= add_ln39_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        convHeight_read_reg_481 <= convHeight;
        convWidth_read_reg_486 <= convWidth;
        empty_35_reg_540 <= empty_35_fu_228_p1;
        empty_37_reg_546 <= empty_37_fu_232_p1;
        empty_39_reg_551 <= empty_39_fu_236_p1;
        empty_40_reg_556 <= empty_40_fu_240_p1;
        empty_reg_534 <= empty_fu_224_p1;
        filters_read_reg_513 <= filters;
        inputHeight_read_reg_493 <= inputHeight;
        inputWidth_read_reg_498 <= inputWidth;
        input_r_read_reg_523 <= input_r;
        numChannels_read_reg_508 <= numChannels;
        numFilters_read_reg_503 <= numFilters;
        output_r_read_reg_518 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_36_reg_609 <= empty_36_fu_305_p2;
        empty_38_reg_614 <= empty_38_fu_310_p2;
        icmp_ln44_reg_629 <= icmp_ln44_fu_315_p2;
        mul_ln18_1_reg_619 <= grp_fu_277_p2;
        mul_ln18_2_reg_624 <= grp_fu_294_p2;
        sub6_reg_603 <= sub6_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        empty_41_reg_710 <= empty_41_fu_433_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        empty_43_reg_676 <= empty_43_fu_377_p1;
        select_ln37_reg_671 <= select_ln37_fu_371_p3;
        tmp_reg_681 <= tmp_fu_381_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_323_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        icmp_ln38_reg_645 <= icmp_ln38_fu_340_p2;
        select_ln37_1_reg_650 <= select_ln37_1_fu_351_p3;
        trunc_ln37_reg_655 <= trunc_ln37_fu_359_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln18_reg_571 <= grp_fu_265_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln37_1_reg_666 <= grp_fu_367_p2;
        mul_ln37_reg_661 <= grp_fu_363_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_cast3_reg_686 <= grp_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_reg_587 <= sub_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        trunc_ln_reg_691 <= {{empty_44_fu_397_p2[31:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((master1_AWREADY == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((master1_WREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((master1_BVALID == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln37_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_363_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce;
    end else begin
        grp_fu_363_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_363_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_363_p0 = trunc_ln37_reg_655;
    end else begin
        grp_fu_363_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_363_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_363_p1 = empty_36_reg_609;
    end else begin
        grp_fu_363_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_367_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce;
    end else begin
        grp_fu_367_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_367_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_367_p0 = trunc_ln37_reg_655;
    end else begin
        grp_fu_367_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_367_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_367_p1 = empty_37_reg_546;
    end else begin
        grp_fu_367_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_386_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce;
    end else begin
        grp_fu_386_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_386_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_386_p0 = empty_38_reg_614;
    end else begin
        grp_fu_386_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_386_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_386_p1 = tmp_reg_681;
    end else begin
        grp_fu_386_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((icmp_ln39_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17)))) begin
        master1_ARVALID = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID;
    end else begin
        master1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((master1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        master1_AWVALID = 1'b1;
    end else begin
        master1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((master1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        master1_BREADY = 1'b1;
    end else begin
        master1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((icmp_ln39_fu_422_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17)))) begin
        master1_RREADY = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY;
    end else begin
        master1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((master1_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        master1_WVALID = 1'b1;
    end else begin
        master1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        master1_blk_n_AW = m_axi_master1_AWREADY;
    end else begin
        master1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        master1_blk_n_B = m_axi_master1_BVALID;
    end else begin
        master1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        master1_blk_n_W = m_axi_master1_WREADY;
    end else begin
        master1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln37_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((master1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln39_fu_422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((master1_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((master1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_1_fu_345_p2 = (iFilter_fu_112 + 32'd1);

assign add_ln37_fu_328_p2 = (indvar_flatten68_fu_116 + 64'd1);

assign add_ln38_fu_438_p2 = (select_ln37_reg_671 + 32'd1);

assign add_ln39_fu_427_p2 = (x_reg_193 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_35_fu_228_p1 = inputWidth[29:0];

assign empty_36_fu_305_p2 = ($signed(empty_reg_534) + $signed(30'd1073741822));

assign empty_37_fu_232_p1 = numChannels[29:0];

assign empty_38_fu_310_p2 = ($signed(empty_35_reg_540) + $signed(30'd1073741822));

assign empty_39_fu_236_p1 = convHeight[29:0];

assign empty_40_fu_240_p1 = convWidth[29:0];

assign empty_41_fu_433_p1 = x_reg_193[29:0];

assign empty_43_fu_377_p1 = select_ln37_fu_371_p3[29:0];

assign empty_44_fu_397_p2 = (tmp_6_fu_390_p3 + output_r_read_reg_518);

assign empty_fu_224_p1 = inputHeight[29:0];

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg;

assign grp_fu_265_p0 = grp_fu_265_p00;

assign grp_fu_265_p00 = convHeight_read_reg_481;

assign grp_fu_265_p1 = grp_fu_265_p10;

assign grp_fu_265_p10 = convWidth_read_reg_486;

assign grp_fu_277_p0 = grp_fu_277_p00;

assign grp_fu_277_p00 = numChannels_read_reg_508;

assign grp_fu_277_p1 = grp_fu_277_p10;

assign grp_fu_277_p10 = mul_ln18_reg_571;

assign grp_fu_294_p0 = grp_fu_294_p00;

assign grp_fu_294_p00 = numFilters_read_reg_503;

assign grp_fu_294_p1 = grp_fu_294_p10;

assign grp_fu_294_p10 = sub_reg_587;

assign icmp_ln37_fu_323_p2 = ((indvar_flatten68_fu_116 == mul_ln18_2_reg_624) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_340_p2 = ((y_fu_108 == sub_reg_587) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_422_p2 = ((x_reg_193 == sub6_reg_603) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_315_p2 = ((convWidth_read_reg_486 == 32'd0) ? 1'b1 : 1'b0);

assign select_ln37_1_fu_351_p3 = ((icmp_ln38_fu_340_p2[0:0] == 1'b1) ? add_ln37_1_fu_345_p2 : iFilter_fu_112);

assign select_ln37_fu_371_p3 = ((icmp_ln38_reg_645[0:0] == 1'b1) ? 32'd0 : y_fu_108);

assign sext_ln39_fu_412_p1 = $signed(trunc_ln_reg_691);

assign sub6_fu_300_p2 = ($signed(inputWidth_read_reg_498) + $signed(32'd4294967294));

assign sub_fu_283_p2 = ($signed(inputHeight_read_reg_493) + $signed(32'd4294967294));

assign tmp_6_fu_390_p3 = {{p_cast3_reg_686}, {2'd0}};

assign tmp_fu_381_p2 = (empty_43_fu_377_p1 + mul_ln37_reg_661);

assign trunc_ln37_fu_359_p1 = select_ln37_1_fu_351_p3[29:0];

endmodule //Conv2D_HW
