-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_master1_AWVALID : OUT STD_LOGIC;
    m_axi_master1_AWREADY : IN STD_LOGIC;
    m_axi_master1_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_WVALID : OUT STD_LOGIC;
    m_axi_master1_WREADY : IN STD_LOGIC;
    m_axi_master1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_WLAST : OUT STD_LOGIC;
    m_axi_master1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_ARVALID : OUT STD_LOGIC;
    m_axi_master1_ARREADY : IN STD_LOGIC;
    m_axi_master1_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_RVALID : IN STD_LOGIC;
    m_axi_master1_RREADY : OUT STD_LOGIC;
    m_axi_master1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_master1_RLAST : IN STD_LOGIC;
    m_axi_master1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_master1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_BVALID : IN STD_LOGIC;
    m_axi_master1_BREADY : OUT STD_LOGIC;
    m_axi_master1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_master1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    tmp_1 : IN STD_LOGIC_VECTOR (29 downto 0);
    mul_ln37_1 : IN STD_LOGIC_VECTOR (29 downto 0);
    tmp_4 : IN STD_LOGIC_VECTOR (29 downto 0);
    y_cast : IN STD_LOGIC_VECTOR (29 downto 0);
    mul_ln18_1 : IN STD_LOGIC_VECTOR (95 downto 0);
    mul_ln18 : IN STD_LOGIC_VECTOR (63 downto 0);
    convWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    icmp_ln44_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    tmp_5 : IN STD_LOGIC_VECTOR (29 downto 0);
    filters : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_2 : IN STD_LOGIC_VECTOR (29 downto 0);
    x_cast : IN STD_LOGIC_VECTOR (29 downto 0);
    input_r : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC;
    grp_fu_363_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_363_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_363_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_363_p_ce : OUT STD_LOGIC;
    grp_fu_367_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_367_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_367_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_367_p_ce : OUT STD_LOGIC;
    grp_fu_386_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_386_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_386_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_386_p_ce : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter5 : BOOLEAN;
    signal ap_block_state14_pp0_stage1_iter6 : BOOLEAN;
    signal ap_block_state16_pp0_stage1_iter7 : BOOLEAN;
    signal ap_block_state18_pp0_stage1_iter8 : BOOLEAN;
    signal ap_block_state20_pp0_stage1_iter9 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln42_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal master1_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal master1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal iChannel_1_reg_745 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal indvar_flatten61_load_reg_750 : STD_LOGIC_VECTOR (95 downto 0);
    signal empty_fu_271_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp5_fu_280_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp5_reg_760 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln42_reg_765 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_765_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln42_1_fu_290_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_1_reg_769 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_33_fu_296_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_33_reg_774 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp5_mid1_fu_300_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp5_mid1_reg_779 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_cast4_reg_784 : STD_LOGIC_VECTOR (29 downto 0);
    signal indvar_flatten_load_reg_789 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln43_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_794 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_794_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_cast_reg_806 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_cast4_mid1_reg_812 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_326_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp6_cast_mid1_reg_817 : STD_LOGIC_VECTOR (29 downto 0);
    signal cx_load_reg_823 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln40_5_fu_429_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln40_5_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln40_7_fu_457_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_7_reg_833 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_8_fu_465_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_8_reg_838 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_6_fu_490_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln40_6_reg_843 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln40_6_reg_843_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_497_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln40_reg_849 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_501_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln40_1_reg_854 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln44_1_mid2_v_reg_859 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln47_fu_569_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln47_reg_864 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln48_fu_583_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln48_reg_875 : STD_LOGIC_VECTOR (31 downto 0);
    signal filterValue_reg_886 : STD_LOGIC_VECTOR (31 downto 0);
    signal pixelValue_reg_891 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1_reg_906 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal acc_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_fu_619_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal cx_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_fu_505_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cy_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_fu_473_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_114 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln43_1_fu_351_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal iChannel_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_fu_330_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten61_fu_122 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln42_fu_309_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal add_ln43_1_fu_346_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp1_fu_366_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_32_fu_370_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp1_mid1_fu_400_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp7_fu_380_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp3_fu_374_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln44_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln40_fu_388_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_435_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln40_2_fu_404_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_34_fu_441_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_1_fu_395_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp7_mid1_fu_451_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_3_fu_411_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp3_mid1_fu_445_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln40_4_fu_417_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal or_ln40_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln44_mid2_v_v_v_v_fu_516_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_fu_523_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln44_mid2_v_fu_528_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln40_1_fu_542_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln44_1_mid2_v_v_v_v_fu_546_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_2_fu_554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln40_fu_538_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln40_1_fu_574_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_600_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_275_ce : STD_LOGIC;
    signal grp_fu_305_ce : STD_LOGIC;
    signal grp_fu_322_ce : STD_LOGIC;
    signal grp_fu_326_ce : STD_LOGIC;
    signal grp_fu_497_ce : STD_LOGIC;
    signal grp_fu_501_ce : STD_LOGIC;
    signal grp_fu_600_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to9 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_mul_30s_30s_30_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component Conv2D_HW_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component Conv2D_HW_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_30s_30s_30_2_1_U4 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp5_mid1_reg_779,
        din1 => tmp_4,
        ce => grp_fu_326_ce,
        dout => grp_fu_326_p2);

    mul_30s_30s_30_2_1_U5 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln40_7_reg_833,
        din1 => tmp_5,
        ce => grp_fu_497_ce,
        dout => grp_fu_497_p2);

    mul_30s_30s_30_2_1_U6 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln40_8_reg_838,
        din1 => tmp_2,
        ce => grp_fu_501_ce,
        dout => grp_fu_501_p2);

    mul_32s_32s_52_2_1_U7 : component Conv2D_HW_mul_32s_32s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => pixelValue_reg_891,
        din1 => filterValue_reg_886,
        ce => grp_fu_600_ce,
        dout => grp_fu_600_p2);

    flow_control_loop_pipe_sequential_init_U : component Conv2D_HW_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                acc_fu_102 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                acc_fu_102 <= acc_1_fu_619_p2;
            end if; 
        end if;
    end process;

    cx_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                cx_fu_106 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                cx_fu_106 <= add_ln44_fu_505_p2;
            end if; 
        end if;
    end process;

    cy_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    cy_fu_110 <= ap_const_lv32_0;
                elsif (((icmp_ln42_reg_765_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    cy_fu_110 <= select_ln43_fu_473_p3;
                end if;
            end if; 
        end if;
    end process;

    iChannel_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    iChannel_fu_118 <= ap_const_lv32_0;
                elsif (((icmp_ln42_reg_765 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    iChannel_fu_118 <= select_ln42_fu_330_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten61_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten61_fu_122 <= ap_const_lv96_0;
                elsif (((icmp_ln42_reg_765 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten61_fu_122 <= add_ln42_fu_309_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_fu_114 <= ap_const_lv64_0;
            elsif (((icmp_ln42_reg_765 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten_fu_114 <= select_ln43_1_fu_351_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln42_fu_285_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln42_1_reg_769 <= add_ln42_1_fu_290_p2;
                empty_33_reg_774 <= empty_33_fu_296_p1;
                tmp5_mid1_reg_779 <= tmp5_mid1_fu_300_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln47_reg_864 <= add_ln47_fu_569_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                filterValue_reg_886 <= m_axi_master1_RDATA;
                iChannel_1_reg_745 <= iChannel_fu_118;
                icmp_ln42_reg_765 <= icmp_ln42_fu_285_p2;
                icmp_ln42_reg_765_pp0_iter1_reg <= icmp_ln42_reg_765;
                icmp_ln42_reg_765_pp0_iter2_reg <= icmp_ln42_reg_765_pp0_iter1_reg;
                icmp_ln42_reg_765_pp0_iter3_reg <= icmp_ln42_reg_765_pp0_iter2_reg;
                icmp_ln42_reg_765_pp0_iter4_reg <= icmp_ln42_reg_765_pp0_iter3_reg;
                icmp_ln42_reg_765_pp0_iter5_reg <= icmp_ln42_reg_765_pp0_iter4_reg;
                icmp_ln42_reg_765_pp0_iter6_reg <= icmp_ln42_reg_765_pp0_iter5_reg;
                icmp_ln42_reg_765_pp0_iter7_reg <= icmp_ln42_reg_765_pp0_iter6_reg;
                indvar_flatten61_load_reg_750 <= indvar_flatten61_fu_122;
                select_ln40_6_reg_843 <= select_ln40_6_fu_490_p3;
                select_ln40_6_reg_843_pp0_iter3_reg <= select_ln40_6_reg_843;
                sext_ln44_1_mid2_v_reg_859 <= add_ln40_2_fu_554_p2(31 downto 2);
                tmp5_reg_760 <= tmp5_fu_280_p2;
                tmp6_cast_reg_806 <= grp_fu_367_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln48_reg_875 <= add_ln48_fu_583_p2;
                icmp_ln43_reg_794_pp0_iter2_reg <= icmp_ln43_reg_794;
                mul_ln40_1_reg_854 <= grp_fu_501_p2;
                mul_ln40_reg_849 <= grp_fu_497_p2;
                p_cast4_reg_784 <= grp_fu_363_p_dout0;
                pixelValue_reg_891 <= m_axi_master1_RDATA;
                trunc_ln1_reg_906 <= grp_fu_600_p2(51 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_765_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cx_load_reg_823 <= cx_fu_106;
                select_ln40_5_reg_828 <= select_ln40_5_fu_429_p3;
                select_ln40_7_reg_833 <= select_ln40_7_fu_457_p3;
                select_ln40_8_reg_838 <= select_ln40_8_fu_465_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_765 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln43_reg_794 <= icmp_ln43_fu_317_p2;
                indvar_flatten_load_reg_789 <= indvar_flatten_fu_114;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_765 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                p_cast4_mid1_reg_812 <= grp_fu_386_p_dout0;
                tmp6_cast_mid1_reg_817 <= grp_fu_326_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to9, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to9 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    acc_1_fu_619_p2 <= std_logic_vector(unsigned(trunc_ln1_reg_906) + unsigned(acc_fu_102));
    acc_out <= acc_fu_102;

    acc_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln42_reg_765_pp0_iter7_reg)
    begin
        if (((icmp_ln42_reg_765_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln40_1_fu_542_p2 <= std_logic_vector(unsigned(mul_ln40_1_reg_854) + unsigned(x_cast));
    add_ln40_2_fu_554_p2 <= std_logic_vector(unsigned(sext_ln44_1_mid2_v_v_v_v_fu_546_p3) + unsigned(input_r));
    add_ln40_fu_523_p2 <= std_logic_vector(unsigned(sext_ln44_mid2_v_v_v_v_fu_516_p3) + unsigned(filters));
    add_ln42_1_fu_290_p2 <= std_logic_vector(unsigned(iChannel_fu_118) + unsigned(ap_const_lv32_1));
    add_ln42_fu_309_p2 <= std_logic_vector(unsigned(indvar_flatten61_load_reg_750) + unsigned(ap_const_lv96_1));
    add_ln43_1_fu_346_p2 <= std_logic_vector(unsigned(indvar_flatten_load_reg_789) + unsigned(ap_const_lv64_1));
    add_ln43_fu_435_p2 <= std_logic_vector(unsigned(select_ln40_fu_388_p3) + unsigned(ap_const_lv32_1));
    add_ln44_fu_505_p2 <= std_logic_vector(unsigned(select_ln40_6_fu_490_p3) + unsigned(ap_const_lv32_1));
    add_ln47_fu_569_p2 <= std_logic_vector(unsigned(select_ln40_6_reg_843) + unsigned(sext_ln40_fu_538_p1));
    add_ln48_fu_583_p2 <= std_logic_vector(unsigned(select_ln40_6_reg_843_pp0_iter3_reg) + unsigned(sext_ln40_1_fu_574_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter8, m_axi_master1_ARREADY, m_axi_master1_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_master1_RVALID = ap_const_logic_0)) or ((m_axi_master1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter8, m_axi_master1_ARREADY, m_axi_master1_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_master1_RVALID = ap_const_logic_0)) or ((m_axi_master1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_master1_RVALID)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (m_axi_master1_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter7, m_axi_master1_ARREADY, m_axi_master1_RVALID)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (m_axi_master1_RVALID = ap_const_logic_0)) or ((m_axi_master1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter7, m_axi_master1_ARREADY, m_axi_master1_RVALID)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (m_axi_master1_RVALID = ap_const_logic_0)) or ((m_axi_master1_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_state10_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage1_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage1_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state16_pp0_stage1_iter7_assign_proc : process(m_axi_master1_RVALID)
    begin
                ap_block_state16_pp0_stage1_iter7 <= (m_axi_master1_RVALID = ap_const_logic_0);
    end process;


    ap_block_state17_pp0_stage0_iter8_assign_proc : process(m_axi_master1_RVALID)
    begin
                ap_block_state17_pp0_stage0_iter8 <= (m_axi_master1_RVALID = ap_const_logic_0);
    end process;

        ap_block_state18_pp0_stage1_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage1_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln42_fu_285_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln42_fu_285_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln42_reg_765_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln42_reg_765_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg, ap_loop_exit_ready_pp0_iter5_reg, ap_loop_exit_ready_pp0_iter6_reg, ap_loop_exit_ready_pp0_iter7_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to9 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to9 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_32_fu_370_p1 <= cy_fu_110(30 - 1 downto 0);
    empty_33_fu_296_p1 <= add_ln42_1_fu_290_p2(30 - 1 downto 0);
    empty_34_fu_441_p1 <= add_ln43_fu_435_p2(30 - 1 downto 0);
    empty_fu_271_p1 <= iChannel_fu_118(30 - 1 downto 0);

    grp_fu_275_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_275_ce <= ap_const_logic_1;
        else 
            grp_fu_275_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_305_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_305_ce <= ap_const_logic_1;
        else 
            grp_fu_305_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_322_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_322_ce <= ap_const_logic_1;
        else 
            grp_fu_322_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_326_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_326_ce <= ap_const_logic_1;
        else 
            grp_fu_326_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_363_p_ce <= grp_fu_275_ce;
    grp_fu_363_p_din0 <= empty_fu_271_p1;
    grp_fu_363_p_din1 <= tmp_1;
    grp_fu_367_p_ce <= grp_fu_305_ce;
    grp_fu_367_p_din0 <= tmp5_reg_760;
    grp_fu_367_p_din1 <= tmp_4;
    grp_fu_386_p_ce <= grp_fu_322_ce;
    grp_fu_386_p_din0 <= empty_33_reg_774;
    grp_fu_386_p_din1 <= tmp_1;

    grp_fu_497_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_497_ce <= ap_const_logic_1;
        else 
            grp_fu_497_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_501_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_501_ce <= ap_const_logic_1;
        else 
            grp_fu_501_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_600_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_600_ce <= ap_const_logic_1;
        else 
            grp_fu_600_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln42_fu_285_p2 <= "1" when (indvar_flatten61_fu_122 = mul_ln18_1) else "0";
    icmp_ln43_fu_317_p2 <= "1" when (indvar_flatten_fu_114 = mul_ln18) else "0";
    icmp_ln44_fu_424_p2 <= "1" when (cx_fu_106 = convWidth) else "0";

    m_axi_master1_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, add_ln47_reg_864, add_ln48_reg_875)
    begin
        if ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                m_axi_master1_ARADDR <= add_ln48_reg_875;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                m_axi_master1_ARADDR <= add_ln47_reg_864;
            else 
                m_axi_master1_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_master1_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_master1_ARBURST <= ap_const_lv2_0;
    m_axi_master1_ARCACHE <= ap_const_lv4_0;
    m_axi_master1_ARID <= ap_const_lv1_0;
    m_axi_master1_ARLEN <= ap_const_lv32_1;
    m_axi_master1_ARLOCK <= ap_const_lv2_0;
    m_axi_master1_ARPROT <= ap_const_lv3_0;
    m_axi_master1_ARQOS <= ap_const_lv4_0;
    m_axi_master1_ARREGION <= ap_const_lv4_0;
    m_axi_master1_ARSIZE <= ap_const_lv3_0;
    m_axi_master1_ARUSER <= ap_const_lv1_0;

    m_axi_master1_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            m_axi_master1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_master1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_master1_AWADDR <= ap_const_lv32_0;
    m_axi_master1_AWBURST <= ap_const_lv2_0;
    m_axi_master1_AWCACHE <= ap_const_lv4_0;
    m_axi_master1_AWID <= ap_const_lv1_0;
    m_axi_master1_AWLEN <= ap_const_lv32_0;
    m_axi_master1_AWLOCK <= ap_const_lv2_0;
    m_axi_master1_AWPROT <= ap_const_lv3_0;
    m_axi_master1_AWQOS <= ap_const_lv4_0;
    m_axi_master1_AWREGION <= ap_const_lv4_0;
    m_axi_master1_AWSIZE <= ap_const_lv3_0;
    m_axi_master1_AWUSER <= ap_const_lv1_0;
    m_axi_master1_AWVALID <= ap_const_logic_0;
    m_axi_master1_BREADY <= ap_const_logic_0;

    m_axi_master1_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            m_axi_master1_RREADY <= ap_const_logic_1;
        else 
            m_axi_master1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_master1_WDATA <= ap_const_lv32_0;
    m_axi_master1_WID <= ap_const_lv1_0;
    m_axi_master1_WLAST <= ap_const_logic_0;
    m_axi_master1_WSTRB <= ap_const_lv4_0;
    m_axi_master1_WUSER <= ap_const_lv1_0;
    m_axi_master1_WVALID <= ap_const_logic_0;

    master1_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, m_axi_master1_ARREADY, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            master1_blk_n_AR <= m_axi_master1_ARREADY;
        else 
            master1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    master1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_CS_fsm_pp0_stage1, m_axi_master1_RVALID, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)))) then 
            master1_blk_n_R <= m_axi_master1_RVALID;
        else 
            master1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    or_ln40_fu_486_p2 <= (select_ln40_5_reg_828 or icmp_ln43_reg_794_pp0_iter2_reg);
    select_ln40_1_fu_395_p3 <= 
        tmp6_cast_mid1_reg_817 when (icmp_ln43_reg_794(0) = '1') else 
        tmp6_cast_reg_806;
    select_ln40_2_fu_404_p3 <= 
        tmp1_mid1_fu_400_p2 when (icmp_ln43_reg_794(0) = '1') else 
        tmp1_fu_366_p2;
    select_ln40_3_fu_411_p3 <= 
        tmp6_cast_mid1_reg_817 when (icmp_ln43_reg_794(0) = '1') else 
        tmp7_fu_380_p2;
    select_ln40_4_fu_417_p3 <= 
        tmp1_mid1_fu_400_p2 when (icmp_ln43_reg_794(0) = '1') else 
        tmp3_fu_374_p2;
    select_ln40_5_fu_429_p3 <= 
        icmp_ln44_1 when (icmp_ln43_reg_794(0) = '1') else 
        icmp_ln44_fu_424_p2;
    select_ln40_6_fu_490_p3 <= 
        ap_const_lv32_0 when (or_ln40_fu_486_p2(0) = '1') else 
        cx_load_reg_823;
    select_ln40_7_fu_457_p3 <= 
        tmp7_mid1_fu_451_p2 when (select_ln40_5_fu_429_p3(0) = '1') else 
        select_ln40_3_fu_411_p3;
    select_ln40_8_fu_465_p3 <= 
        tmp3_mid1_fu_445_p2 when (select_ln40_5_fu_429_p3(0) = '1') else 
        select_ln40_4_fu_417_p3;
    select_ln40_fu_388_p3 <= 
        ap_const_lv32_0 when (icmp_ln43_reg_794(0) = '1') else 
        cy_fu_110;
    select_ln42_fu_330_p3 <= 
        add_ln42_1_reg_769 when (icmp_ln43_fu_317_p2(0) = '1') else 
        iChannel_1_reg_745;
    select_ln43_1_fu_351_p3 <= 
        ap_const_lv64_1 when (icmp_ln43_reg_794(0) = '1') else 
        add_ln43_1_fu_346_p2;
    select_ln43_fu_473_p3 <= 
        add_ln43_fu_435_p2 when (select_ln40_5_fu_429_p3(0) = '1') else 
        select_ln40_fu_388_p3;
        sext_ln40_1_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_1_mid2_v_reg_859),32));

        sext_ln40_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_mid2_v_fu_528_p4),32));

    sext_ln44_1_mid2_v_v_v_v_fu_546_p3 <= (add_ln40_1_fu_542_p2 & ap_const_lv2_0);
    sext_ln44_mid2_v_fu_528_p4 <= add_ln40_fu_523_p2(31 downto 2);
    sext_ln44_mid2_v_v_v_v_fu_516_p3 <= (mul_ln40_reg_849 & ap_const_lv2_0);
    tmp1_fu_366_p2 <= std_logic_vector(unsigned(y_cast) + unsigned(p_cast4_reg_784));
    tmp1_mid1_fu_400_p2 <= std_logic_vector(unsigned(y_cast) + unsigned(p_cast4_mid1_reg_812));
    tmp3_fu_374_p2 <= std_logic_vector(unsigned(tmp1_fu_366_p2) + unsigned(empty_32_fu_370_p1));
    tmp3_mid1_fu_445_p2 <= std_logic_vector(unsigned(select_ln40_2_fu_404_p3) + unsigned(empty_34_fu_441_p1));
    tmp5_fu_280_p2 <= std_logic_vector(signed(empty_fu_271_p1) + signed(mul_ln37_1));
    tmp5_mid1_fu_300_p2 <= std_logic_vector(signed(empty_33_fu_296_p1) + signed(mul_ln37_1));
    tmp7_fu_380_p2 <= std_logic_vector(unsigned(empty_32_fu_370_p1) + unsigned(tmp6_cast_reg_806));
    tmp7_mid1_fu_451_p2 <= std_logic_vector(unsigned(empty_34_fu_441_p1) + unsigned(select_ln40_1_fu_395_p3));
end behav;
