-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW is
generic (
    C_M_AXI_MASTER1_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_MASTER1_ID_WIDTH : INTEGER := 1;
    C_M_AXI_MASTER1_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MASTER1_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_MASTER1_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MASTER1_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MASTER1_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MASTER1_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_MASTER1_USER_VALUE : INTEGER := 0;
    C_M_AXI_MASTER1_PROT_VALUE : INTEGER := 0;
    C_M_AXI_MASTER1_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_master1_AWVALID : OUT STD_LOGIC;
    m_axi_master1_AWREADY : IN STD_LOGIC;
    m_axi_master1_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ADDR_WIDTH-1 downto 0);
    m_axi_master1_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ID_WIDTH-1 downto 0);
    m_axi_master1_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_master1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_AWUSER_WIDTH-1 downto 0);
    m_axi_master1_WVALID : OUT STD_LOGIC;
    m_axi_master1_WREADY : IN STD_LOGIC;
    m_axi_master1_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_DATA_WIDTH-1 downto 0);
    m_axi_master1_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_DATA_WIDTH/8-1 downto 0);
    m_axi_master1_WLAST : OUT STD_LOGIC;
    m_axi_master1_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ID_WIDTH-1 downto 0);
    m_axi_master1_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_WUSER_WIDTH-1 downto 0);
    m_axi_master1_ARVALID : OUT STD_LOGIC;
    m_axi_master1_ARREADY : IN STD_LOGIC;
    m_axi_master1_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ADDR_WIDTH-1 downto 0);
    m_axi_master1_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ID_WIDTH-1 downto 0);
    m_axi_master1_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_master1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_master1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_master1_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ARUSER_WIDTH-1 downto 0);
    m_axi_master1_RVALID : IN STD_LOGIC;
    m_axi_master1_RREADY : OUT STD_LOGIC;
    m_axi_master1_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_MASTER1_DATA_WIDTH-1 downto 0);
    m_axi_master1_RLAST : IN STD_LOGIC;
    m_axi_master1_RID : IN STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ID_WIDTH-1 downto 0);
    m_axi_master1_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_MASTER1_RUSER_WIDTH-1 downto 0);
    m_axi_master1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_BVALID : IN STD_LOGIC;
    m_axi_master1_BREADY : OUT STD_LOGIC;
    m_axi_master1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_master1_BID : IN STD_LOGIC_VECTOR (C_M_AXI_MASTER1_ID_WIDTH-1 downto 0);
    m_axi_master1_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_MASTER1_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5330,HLS_SYN_LUT=4938,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (23 downto 0) := "000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (23 downto 0) := "000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (23 downto 0) := "000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (23 downto 0) := "000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (23 downto 0) := "000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (23 downto 0) := "000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (23 downto 0) := "000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (23 downto 0) := "000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (23 downto 0) := "000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (23 downto 0) := "001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (23 downto 0) := "010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111110";
    constant ap_const_lv30_3FFFFFFE : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111111111111110";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal input_r : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r : STD_LOGIC_VECTOR (31 downto 0);
    signal filters : STD_LOGIC_VECTOR (31 downto 0);
    signal numChannels : STD_LOGIC_VECTOR (31 downto 0);
    signal numFilters : STD_LOGIC_VECTOR (31 downto 0);
    signal inputWidth : STD_LOGIC_VECTOR (31 downto 0);
    signal inputHeight : STD_LOGIC_VECTOR (31 downto 0);
    signal convWidth : STD_LOGIC_VECTOR (31 downto 0);
    signal convHeight : STD_LOGIC_VECTOR (31 downto 0);
    signal master1_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal master1_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal master1_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal convHeight_read_reg_481 : STD_LOGIC_VECTOR (31 downto 0);
    signal convWidth_read_reg_486 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputHeight_read_reg_493 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputWidth_read_reg_498 : STD_LOGIC_VECTOR (31 downto 0);
    signal numFilters_read_reg_503 : STD_LOGIC_VECTOR (31 downto 0);
    signal numChannels_read_reg_508 : STD_LOGIC_VECTOR (31 downto 0);
    signal filters_read_reg_513 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r_read_reg_518 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_read_reg_523 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_224_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_reg_534 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_35_fu_228_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_35_reg_540 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_37_fu_232_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_37_reg_546 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_39_fu_236_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_39_reg_551 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_40_fu_240_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_40_reg_556 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_265_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln18_reg_571 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sub_fu_283_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_587 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sub6_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub6_reg_603 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal empty_36_fu_305_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_36_reg_609 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_38_fu_310_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_38_reg_614 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal mul_ln18_1_reg_619 : STD_LOGIC_VECTOR (95 downto 0);
    signal grp_fu_294_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln18_2_reg_624 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln44_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_reg_629 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln37_fu_328_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln37_reg_637 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln38_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_1_fu_351_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln37_1_reg_650 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln37_fu_359_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln37_reg_655 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_363_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln37_reg_661 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_fu_367_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln37_1_reg_666 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln37_fu_371_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln37_reg_671 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal empty_43_fu_377_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_43_reg_676 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_381_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_reg_681 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_386_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_cast3_reg_686 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal trunc_ln_reg_691 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal add_ln39_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln39_reg_705 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal empty_41_fu_433_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal empty_41_reg_710 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln39_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_idle : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWVALID : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WVALID : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WLAST : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_BREADY : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out_ap_vld : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce : STD_LOGIC;
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce : STD_LOGIC;
    signal master1_AWVALID : STD_LOGIC;
    signal master1_AWREADY : STD_LOGIC;
    signal master1_WVALID : STD_LOGIC;
    signal master1_WREADY : STD_LOGIC;
    signal master1_ARVALID : STD_LOGIC;
    signal master1_ARREADY : STD_LOGIC;
    signal master1_RVALID : STD_LOGIC;
    signal master1_RREADY : STD_LOGIC;
    signal master1_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal master1_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal master1_BVALID : STD_LOGIC;
    signal master1_BREADY : STD_LOGIC;
    signal x_reg_193 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal sext_ln39_fu_412_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln38_fu_438_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal iFilter_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten68_fu_116 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_265_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_265_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_277_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_294_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_294_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln37_1_fu_345_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_363_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_363_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_367_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_367_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_386_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_386_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal tmp_6_fu_390_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_44_fu_397_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_363_ce : STD_LOGIC;
    signal grp_fu_367_ce : STD_LOGIC;
    signal grp_fu_386_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal grp_fu_265_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_265_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_277_p00 : STD_LOGIC_VECTOR (95 downto 0);
    signal grp_fu_277_p10 : STD_LOGIC_VECTOR (95 downto 0);
    signal grp_fu_294_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_294_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_master1_AWVALID : OUT STD_LOGIC;
        m_axi_master1_AWREADY : IN STD_LOGIC;
        m_axi_master1_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_master1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_master1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_WVALID : OUT STD_LOGIC;
        m_axi_master1_WREADY : IN STD_LOGIC;
        m_axi_master1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_WLAST : OUT STD_LOGIC;
        m_axi_master1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_ARVALID : OUT STD_LOGIC;
        m_axi_master1_ARREADY : IN STD_LOGIC;
        m_axi_master1_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_master1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_master1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_master1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_RVALID : IN STD_LOGIC;
        m_axi_master1_RREADY : OUT STD_LOGIC;
        m_axi_master1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_master1_RLAST : IN STD_LOGIC;
        m_axi_master1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_master1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_BVALID : IN STD_LOGIC;
        m_axi_master1_BREADY : OUT STD_LOGIC;
        m_axi_master1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_master1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_master1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        tmp_1 : IN STD_LOGIC_VECTOR (29 downto 0);
        mul_ln37_1 : IN STD_LOGIC_VECTOR (29 downto 0);
        tmp_4 : IN STD_LOGIC_VECTOR (29 downto 0);
        y_cast : IN STD_LOGIC_VECTOR (29 downto 0);
        mul_ln18_1 : IN STD_LOGIC_VECTOR (95 downto 0);
        mul_ln18 : IN STD_LOGIC_VECTOR (63 downto 0);
        convWidth : IN STD_LOGIC_VECTOR (31 downto 0);
        icmp_ln44_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        tmp_5 : IN STD_LOGIC_VECTOR (29 downto 0);
        filters : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_2 : IN STD_LOGIC_VECTOR (29 downto 0);
        x_cast : IN STD_LOGIC_VECTOR (29 downto 0);
        input_r : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_out_ap_vld : OUT STD_LOGIC;
        grp_fu_363_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_363_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_363_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_363_p_ce : OUT STD_LOGIC;
        grp_fu_367_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_367_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_367_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_367_p_ce : OUT STD_LOGIC;
        grp_fu_386_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_386_p_din1 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_386_p_dout0 : IN STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_386_p_ce : OUT STD_LOGIC );
    end component;


    component Conv2D_HW_mul_32ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Conv2D_HW_mul_32ns_64ns_96_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (95 downto 0) );
    end component;


    component Conv2D_HW_mul_30s_30s_30_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component Conv2D_HW_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        input_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        filters : OUT STD_LOGIC_VECTOR (31 downto 0);
        numChannels : OUT STD_LOGIC_VECTOR (31 downto 0);
        numFilters : OUT STD_LOGIC_VECTOR (31 downto 0);
        inputWidth : OUT STD_LOGIC_VECTOR (31 downto 0);
        inputHeight : OUT STD_LOGIC_VECTOR (31 downto 0);
        convWidth : OUT STD_LOGIC_VECTOR (31 downto 0);
        convHeight : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component Conv2D_HW_master1_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        USER_RFIFONUM_WIDTH : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204 : component Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start,
        ap_done => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done,
        ap_idle => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_idle,
        ap_ready => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready,
        m_axi_master1_AWVALID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWVALID,
        m_axi_master1_AWREADY => ap_const_logic_0,
        m_axi_master1_AWADDR => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWADDR,
        m_axi_master1_AWID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWID,
        m_axi_master1_AWLEN => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLEN,
        m_axi_master1_AWSIZE => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWSIZE,
        m_axi_master1_AWBURST => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWBURST,
        m_axi_master1_AWLOCK => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWLOCK,
        m_axi_master1_AWCACHE => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWCACHE,
        m_axi_master1_AWPROT => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWPROT,
        m_axi_master1_AWQOS => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWQOS,
        m_axi_master1_AWREGION => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWREGION,
        m_axi_master1_AWUSER => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_AWUSER,
        m_axi_master1_WVALID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WVALID,
        m_axi_master1_WREADY => ap_const_logic_0,
        m_axi_master1_WDATA => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WDATA,
        m_axi_master1_WSTRB => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WSTRB,
        m_axi_master1_WLAST => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WLAST,
        m_axi_master1_WID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WID,
        m_axi_master1_WUSER => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_WUSER,
        m_axi_master1_ARVALID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID,
        m_axi_master1_ARREADY => master1_ARREADY,
        m_axi_master1_ARADDR => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR,
        m_axi_master1_ARID => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARID,
        m_axi_master1_ARLEN => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN,
        m_axi_master1_ARSIZE => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARSIZE,
        m_axi_master1_ARBURST => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARBURST,
        m_axi_master1_ARLOCK => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLOCK,
        m_axi_master1_ARCACHE => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARCACHE,
        m_axi_master1_ARPROT => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARPROT,
        m_axi_master1_ARQOS => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARQOS,
        m_axi_master1_ARREGION => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARREGION,
        m_axi_master1_ARUSER => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARUSER,
        m_axi_master1_RVALID => master1_RVALID,
        m_axi_master1_RREADY => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY,
        m_axi_master1_RDATA => master1_RDATA,
        m_axi_master1_RLAST => ap_const_logic_0,
        m_axi_master1_RID => ap_const_lv1_0,
        m_axi_master1_RFIFONUM => master1_RFIFONUM,
        m_axi_master1_RUSER => ap_const_lv1_0,
        m_axi_master1_RRESP => ap_const_lv2_0,
        m_axi_master1_BVALID => ap_const_logic_0,
        m_axi_master1_BREADY => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_BREADY,
        m_axi_master1_BRESP => ap_const_lv2_0,
        m_axi_master1_BID => ap_const_lv1_0,
        m_axi_master1_BUSER => ap_const_lv1_0,
        tmp_1 => empty_reg_534,
        mul_ln37_1 => mul_ln37_1_reg_666,
        tmp_4 => empty_39_reg_551,
        y_cast => empty_43_reg_676,
        mul_ln18_1 => mul_ln18_1_reg_619,
        mul_ln18 => mul_ln18_reg_571,
        convWidth => convWidth_read_reg_486,
        icmp_ln44_1 => icmp_ln44_reg_629,
        tmp_5 => empty_40_reg_556,
        filters => filters_read_reg_513,
        tmp_2 => empty_35_reg_540,
        x_cast => empty_41_reg_710,
        input_r => input_r_read_reg_523,
        acc_out => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out,
        acc_out_ap_vld => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out_ap_vld,
        grp_fu_363_p_din0 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0,
        grp_fu_363_p_din1 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1,
        grp_fu_363_p_dout0 => grp_fu_363_p2,
        grp_fu_363_p_ce => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce,
        grp_fu_367_p_din0 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0,
        grp_fu_367_p_din1 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1,
        grp_fu_367_p_dout0 => grp_fu_367_p2,
        grp_fu_367_p_ce => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce,
        grp_fu_386_p_din0 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0,
        grp_fu_386_p_din1 => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1,
        grp_fu_386_p_dout0 => grp_fu_386_p2,
        grp_fu_386_p_ce => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce);

    control_s_axi_U : component Conv2D_HW_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        input_r => input_r,
        output_r => output_r,
        filters => filters,
        numChannels => numChannels,
        numFilters => numFilters,
        inputWidth => inputWidth,
        inputHeight => inputHeight,
        convWidth => convWidth,
        convHeight => convHeight,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    master1_m_axi_U : component Conv2D_HW_master1_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 5,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_MASTER1_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_MASTER1_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_MASTER1_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_MASTER1_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_MASTER1_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_MASTER1_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_MASTER1_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_MASTER1_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_MASTER1_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_MASTER1_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_MASTER1_CACHE_VALUE,
        USER_RFIFONUM_WIDTH => 9,
        USER_DW => 32,
        USER_AW => 32,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_master1_AWVALID,
        AWREADY => m_axi_master1_AWREADY,
        AWADDR => m_axi_master1_AWADDR,
        AWID => m_axi_master1_AWID,
        AWLEN => m_axi_master1_AWLEN,
        AWSIZE => m_axi_master1_AWSIZE,
        AWBURST => m_axi_master1_AWBURST,
        AWLOCK => m_axi_master1_AWLOCK,
        AWCACHE => m_axi_master1_AWCACHE,
        AWPROT => m_axi_master1_AWPROT,
        AWQOS => m_axi_master1_AWQOS,
        AWREGION => m_axi_master1_AWREGION,
        AWUSER => m_axi_master1_AWUSER,
        WVALID => m_axi_master1_WVALID,
        WREADY => m_axi_master1_WREADY,
        WDATA => m_axi_master1_WDATA,
        WSTRB => m_axi_master1_WSTRB,
        WLAST => m_axi_master1_WLAST,
        WID => m_axi_master1_WID,
        WUSER => m_axi_master1_WUSER,
        ARVALID => m_axi_master1_ARVALID,
        ARREADY => m_axi_master1_ARREADY,
        ARADDR => m_axi_master1_ARADDR,
        ARID => m_axi_master1_ARID,
        ARLEN => m_axi_master1_ARLEN,
        ARSIZE => m_axi_master1_ARSIZE,
        ARBURST => m_axi_master1_ARBURST,
        ARLOCK => m_axi_master1_ARLOCK,
        ARCACHE => m_axi_master1_ARCACHE,
        ARPROT => m_axi_master1_ARPROT,
        ARQOS => m_axi_master1_ARQOS,
        ARREGION => m_axi_master1_ARREGION,
        ARUSER => m_axi_master1_ARUSER,
        RVALID => m_axi_master1_RVALID,
        RREADY => m_axi_master1_RREADY,
        RDATA => m_axi_master1_RDATA,
        RLAST => m_axi_master1_RLAST,
        RID => m_axi_master1_RID,
        RUSER => m_axi_master1_RUSER,
        RRESP => m_axi_master1_RRESP,
        BVALID => m_axi_master1_BVALID,
        BREADY => m_axi_master1_BREADY,
        BRESP => m_axi_master1_BRESP,
        BID => m_axi_master1_BID,
        BUSER => m_axi_master1_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => master1_ARVALID,
        I_ARREADY => master1_ARREADY,
        I_ARADDR => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARADDR,
        I_ARLEN => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARLEN,
        I_RVALID => master1_RVALID,
        I_RREADY => master1_RREADY,
        I_RDATA => master1_RDATA,
        I_RFIFONUM => master1_RFIFONUM,
        I_AWVALID => master1_AWVALID,
        I_AWREADY => master1_AWREADY,
        I_AWADDR => sext_ln39_fu_412_p1,
        I_AWLEN => sub6_reg_603,
        I_WVALID => master1_WVALID,
        I_WREADY => master1_WREADY,
        I_WDATA => grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_acc_out,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => master1_BVALID,
        I_BREADY => master1_BREADY);

    mul_32ns_32ns_64_2_1_U25 : component Conv2D_HW_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_265_p0,
        din1 => grp_fu_265_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_265_p2);

    mul_32ns_64ns_96_5_1_U26 : component Conv2D_HW_mul_32ns_64ns_96_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 64,
        dout_WIDTH => 96)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_277_p0,
        din1 => grp_fu_277_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_277_p2);

    mul_32ns_32ns_64_2_1_U27 : component Conv2D_HW_mul_32ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_294_p0,
        din1 => grp_fu_294_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_294_p2);

    mul_30s_30s_30_2_1_U28 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_363_p0,
        din1 => grp_fu_363_p1,
        ce => grp_fu_363_ce,
        dout => grp_fu_363_p2);

    mul_30s_30s_30_2_1_U29 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_367_p0,
        din1 => grp_fu_367_p1,
        ce => grp_fu_367_ce,
        dout => grp_fu_367_p2);

    mul_30s_30s_30_2_1_U30 : component Conv2D_HW_mul_30s_30s_30_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 30,
        din1_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_386_p0,
        din1 => grp_fu_386_p1,
        ce => grp_fu_386_ce,
        dout => grp_fu_386_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln39_fu_422_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_ready = ap_const_logic_1)) then 
                    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    iFilter_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                iFilter_fu_112 <= ap_const_lv32_0;
            elsif (((icmp_ln39_fu_422_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                iFilter_fu_112 <= select_ln37_1_reg_650;
            end if; 
        end if;
    end process;

    indvar_flatten68_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten68_fu_116 <= ap_const_lv64_0;
            elsif (((icmp_ln39_fu_422_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                indvar_flatten68_fu_116 <= add_ln37_reg_637;
            end if; 
        end if;
    end process;

    x_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((master1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                x_reg_193 <= ap_const_lv32_0;
            elsif (((master1_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
                x_reg_193 <= add_ln39_reg_705;
            end if; 
        end if;
    end process;

    y_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_108 <= ap_const_lv32_0;
            elsif (((icmp_ln39_fu_422_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                y_fu_108 <= add_ln38_fu_438_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                add_ln37_reg_637 <= add_ln37_fu_328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                add_ln39_reg_705 <= add_ln39_fu_427_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                convHeight_read_reg_481 <= convHeight;
                convWidth_read_reg_486 <= convWidth;
                empty_35_reg_540 <= empty_35_fu_228_p1;
                empty_37_reg_546 <= empty_37_fu_232_p1;
                empty_39_reg_551 <= empty_39_fu_236_p1;
                empty_40_reg_556 <= empty_40_fu_240_p1;
                empty_reg_534 <= empty_fu_224_p1;
                filters_read_reg_513 <= filters;
                inputHeight_read_reg_493 <= inputHeight;
                inputWidth_read_reg_498 <= inputWidth;
                input_r_read_reg_523 <= input_r;
                numChannels_read_reg_508 <= numChannels;
                numFilters_read_reg_503 <= numFilters;
                output_r_read_reg_518 <= output_r;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                empty_36_reg_609 <= empty_36_fu_305_p2;
                empty_38_reg_614 <= empty_38_fu_310_p2;
                icmp_ln44_reg_629 <= icmp_ln44_fu_315_p2;
                mul_ln18_1_reg_619 <= grp_fu_277_p2;
                mul_ln18_2_reg_624 <= grp_fu_294_p2;
                sub6_reg_603 <= sub6_fu_300_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_422_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                empty_41_reg_710 <= empty_41_fu_433_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                empty_43_reg_676 <= empty_43_fu_377_p1;
                select_ln37_reg_671 <= select_ln37_fu_371_p3;
                tmp_reg_681 <= tmp_fu_381_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                icmp_ln38_reg_645 <= icmp_ln38_fu_340_p2;
                select_ln37_1_reg_650 <= select_ln37_1_fu_351_p3;
                trunc_ln37_reg_655 <= trunc_ln37_fu_359_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln18_reg_571 <= grp_fu_265_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                mul_ln37_1_reg_666 <= grp_fu_367_p2;
                mul_ln37_reg_661 <= grp_fu_363_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                p_cast3_reg_686 <= grp_fu_386_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                sub_reg_587 <= sub_fu_283_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                trunc_ln_reg_691 <= empty_44_fu_397_p2(31 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state19, ap_CS_fsm_state24, ap_CS_fsm_state16, ap_CS_fsm_state9, icmp_ln37_fu_323_p2, ap_CS_fsm_state17, icmp_ln39_fu_422_p2, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done, master1_AWREADY, master1_WREADY, master1_BVALID, ap_CS_fsm_state18)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((icmp_ln37_fu_323_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((master1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln39_fu_422_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state19 => 
                if (((master1_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                if (((master1_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln37_1_fu_345_p2 <= std_logic_vector(unsigned(iFilter_fu_112) + unsigned(ap_const_lv32_1));
    add_ln37_fu_328_p2 <= std_logic_vector(unsigned(indvar_flatten68_fu_116) + unsigned(ap_const_lv64_1));
    add_ln38_fu_438_p2 <= std_logic_vector(unsigned(select_ln37_reg_671) + unsigned(ap_const_lv32_1));
    add_ln39_fu_427_p2 <= std_logic_vector(unsigned(x_reg_193) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(master1_AWREADY)
    begin
        if ((master1_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state17_blk <= ap_const_logic_0;

    ap_ST_fsm_state18_blk_assign_proc : process(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done)
    begin
        if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state18_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state18_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state19_blk_assign_proc : process(master1_WREADY)
    begin
        if ((master1_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;

    ap_ST_fsm_state24_blk_assign_proc : process(master1_BVALID)
    begin
        if ((master1_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state24_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state24_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state9, icmp_ln37_fu_323_p2)
    begin
        if (((icmp_ln37_fu_323_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9, icmp_ln37_fu_323_p2)
    begin
        if (((icmp_ln37_fu_323_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_35_fu_228_p1 <= inputWidth(30 - 1 downto 0);
    empty_36_fu_305_p2 <= std_logic_vector(unsigned(empty_reg_534) + unsigned(ap_const_lv30_3FFFFFFE));
    empty_37_fu_232_p1 <= numChannels(30 - 1 downto 0);
    empty_38_fu_310_p2 <= std_logic_vector(unsigned(empty_35_reg_540) + unsigned(ap_const_lv30_3FFFFFFE));
    empty_39_fu_236_p1 <= convHeight(30 - 1 downto 0);
    empty_40_fu_240_p1 <= convWidth(30 - 1 downto 0);
    empty_41_fu_433_p1 <= x_reg_193(30 - 1 downto 0);
    empty_43_fu_377_p1 <= select_ln37_fu_371_p3(30 - 1 downto 0);
    empty_44_fu_397_p2 <= std_logic_vector(unsigned(tmp_6_fu_390_p3) + unsigned(output_r_read_reg_518));
    empty_fu_224_p1 <= inputHeight(30 - 1 downto 0);
    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_ap_start_reg;
    grp_fu_265_p0 <= grp_fu_265_p00(32 - 1 downto 0);
    grp_fu_265_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(convHeight_read_reg_481),64));
    grp_fu_265_p1 <= grp_fu_265_p10(32 - 1 downto 0);
    grp_fu_265_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(convWidth_read_reg_486),64));
    grp_fu_277_p0 <= grp_fu_277_p00(32 - 1 downto 0);
    grp_fu_277_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(numChannels_read_reg_508),96));
    grp_fu_277_p1 <= grp_fu_277_p10(64 - 1 downto 0);
    grp_fu_277_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln18_reg_571),96));
    grp_fu_294_p0 <= grp_fu_294_p00(32 - 1 downto 0);
    grp_fu_294_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(numFilters_read_reg_503),64));
    grp_fu_294_p1 <= grp_fu_294_p10(32 - 1 downto 0);
    grp_fu_294_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_reg_587),64));

    grp_fu_363_ce_assign_proc : process(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_363_ce <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_ce;
        else 
            grp_fu_363_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_363_p0_assign_proc : process(trunc_ln37_reg_655, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0, ap_CS_fsm_state18, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_363_p0 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_363_p0 <= trunc_ln37_reg_655;
        else 
            grp_fu_363_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_363_p1_assign_proc : process(empty_36_reg_609, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1, ap_CS_fsm_state18, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_363_p1 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_363_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_363_p1 <= empty_36_reg_609;
        else 
            grp_fu_363_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_367_ce_assign_proc : process(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_367_ce <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_ce;
        else 
            grp_fu_367_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_367_p0_assign_proc : process(trunc_ln37_reg_655, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0, ap_CS_fsm_state18, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_367_p0 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_367_p0 <= trunc_ln37_reg_655;
        else 
            grp_fu_367_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_367_p1_assign_proc : process(empty_37_reg_546, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1, ap_CS_fsm_state18, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_367_p1 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_367_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_367_p1 <= empty_37_reg_546;
        else 
            grp_fu_367_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_386_ce_assign_proc : process(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_386_ce <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_ce;
        else 
            grp_fu_386_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_386_p0_assign_proc : process(empty_38_reg_614, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0, ap_CS_fsm_state18, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_386_p0 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_386_p0 <= empty_38_reg_614;
        else 
            grp_fu_386_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_386_p1_assign_proc : process(tmp_reg_681, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1, ap_CS_fsm_state18, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_386_p1 <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_grp_fu_386_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_386_p1 <= tmp_reg_681;
        else 
            grp_fu_386_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln37_fu_323_p2 <= "1" when (indvar_flatten68_fu_116 = mul_ln18_2_reg_624) else "0";
    icmp_ln38_fu_340_p2 <= "1" when (y_fu_108 = sub_reg_587) else "0";
    icmp_ln39_fu_422_p2 <= "1" when (x_reg_193 = sub6_reg_603) else "0";
    icmp_ln44_fu_315_p2 <= "1" when (convWidth_read_reg_486 = ap_const_lv32_0) else "0";

    master1_ARVALID_assign_proc : process(ap_CS_fsm_state17, icmp_ln39_fu_422_p2, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((icmp_ln39_fu_422_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17)))) then 
            master1_ARVALID <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_ARVALID;
        else 
            master1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    master1_AWVALID_assign_proc : process(ap_CS_fsm_state16, master1_AWREADY)
    begin
        if (((master1_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            master1_AWVALID <= ap_const_logic_1;
        else 
            master1_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    master1_BREADY_assign_proc : process(ap_CS_fsm_state24, master1_BVALID)
    begin
        if (((master1_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then 
            master1_BREADY <= ap_const_logic_1;
        else 
            master1_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    master1_RREADY_assign_proc : process(ap_CS_fsm_state17, icmp_ln39_fu_422_p2, grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or ((icmp_ln39_fu_422_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17)))) then 
            master1_RREADY <= grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_204_m_axi_master1_RREADY;
        else 
            master1_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    master1_WVALID_assign_proc : process(ap_CS_fsm_state19, master1_WREADY)
    begin
        if (((master1_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            master1_WVALID <= ap_const_logic_1;
        else 
            master1_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    master1_blk_n_AW_assign_proc : process(m_axi_master1_AWREADY, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            master1_blk_n_AW <= m_axi_master1_AWREADY;
        else 
            master1_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    master1_blk_n_B_assign_proc : process(m_axi_master1_BVALID, ap_CS_fsm_state24)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            master1_blk_n_B <= m_axi_master1_BVALID;
        else 
            master1_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    master1_blk_n_W_assign_proc : process(m_axi_master1_WREADY, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            master1_blk_n_W <= m_axi_master1_WREADY;
        else 
            master1_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    select_ln37_1_fu_351_p3 <= 
        add_ln37_1_fu_345_p2 when (icmp_ln38_fu_340_p2(0) = '1') else 
        iFilter_fu_112;
    select_ln37_fu_371_p3 <= 
        ap_const_lv32_0 when (icmp_ln38_reg_645(0) = '1') else 
        y_fu_108;
        sext_ln39_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_691),32));

    sub6_fu_300_p2 <= std_logic_vector(unsigned(inputWidth_read_reg_498) + unsigned(ap_const_lv32_FFFFFFFE));
    sub_fu_283_p2 <= std_logic_vector(unsigned(inputHeight_read_reg_493) + unsigned(ap_const_lv32_FFFFFFFE));
    tmp_6_fu_390_p3 <= (p_cast3_reg_686 & ap_const_lv2_0);
    tmp_fu_381_p2 <= std_logic_vector(unsigned(empty_43_fu_377_p1) + unsigned(mul_ln37_reg_661));
    trunc_ln37_fu_359_p1 <= select_ln37_1_fu_351_p3(30 - 1 downto 0);
end behav;
